// Generic reference material for the execution recipe. It deliberately contains
// no proof-specific status, node number, or named current residual.
export const SELECTION_ROWS = [
  ["A bounded or finite object", "Test a direct target hit, contextual distinction, silent compression, then enumerate the remaining bounded configurations", "Prove hit/defect/compression is exhaustive; use the actual parameters; give every survivor a structural consumer rather than enumerating it again"],
  ["A long chain or corridor of finitely typed states", "Prove termination or finite-state pumping; extract the first repeat or boundary event; route by hit, defect or compression", "Prove that the first event exists; preserve the state carried at the repeat; cover equal-length and degenerate exchanges"],
  ["Overlapping or nonadditive supports", "Retain the first failing fiber, extract a minimal connected overlap obstruction, uncross it into a serial system, then apply arithmetic or a periodic response classification", "Prove connectivity, charge each saving once, construct the actual serial system, and use the full modulus and range required by the arithmetic"],
  ["A same-size competitor invisible to the current order", "Refine the order by a canonical invariant, perform the exchange, and prove strict decrease of that invariant", "Recheck every earlier use of minimality against the refined order"],
  ["An asymptotic side condition", "Exactify the condition as an integer inequality on the retained object; treat its failure as a structural residual", "Every allowance must be a quantity carried exactly by the branch, and the failure must supply data consumed by the next move"],
  ["A discarded remainder or extraction loss", "Charge it into an existing ledger with a no-overcount lemma, or retain it as a typed residual", "The receiving ledger must accept the exact witness and the loss must not also be counted where it was discarded"],
  ["A downstream step reads a bound through one inequality", "Supply that inequality from the new branch and reuse the continuation only after checking every other quantity it reads", "Trace all consumers; give any additional use its own branch test"],
  ["A residual class that survives but is small", "Compare aggregate capacity with the deficit using one currency and one scale", "Prove the capacity and deficit refer to the same class, object and multiplicity"],
  ["A loop with no obvious end", "Choose a nonnegative integer measure, prove strict decrease, and restore every standing invariant after each pass", "The measure must be on the retained bookkeeping and every charge update must be exact"],
  ["A residual coincides with an excluded alternative", "Identify it with that alternative by proving every defining witness and interface field", "Use declared witnesses from the branch; never reconstruct a missing witness from a different object"],
  ["Many bounded components of a relabeling-stable class", "Use orbit counting or an invariant code to compare the class with its budget", "Bound automorphisms, prove relabeling invariance, and ensure the counted class is exactly the budgeted class"],
  ["No bounded local test detects a defect", "Apply an entropy or compression squeeze in the correctly charged class", "Verify the class is not already charged and test the threshold on a sanity family"],
  ["A minimal object has a bounded-degree region but no arithmetic hit", "Run every applicable deletion, contraction and replacement move", "Check simplicity, minimum degree, target preservation and strict decrease for each move"],
  ["A high-degree vertex appears in a low-degree argument", "Split on whether the relevant support meets the high-degree set; route the high-degree arm through an actual handoff", "Construct separated connector tails and prove the handoff consumes a finite token set"],
  ["Loss of compactness or failure of an analytic representative", "Separate concentration, translation, scale, profile, weak-to-strong and gauge defects; normalize and consume a bounded resource on each arm", "Preserve topology, normalization, gauge and observer data across every transition"]
] as const;

export const MOVE_RULES = [
  "**Use only branch-state facts, fixed inputs, and textbook material.** A move that needs an unlisted global result is a defect in the case structure, not a closure.",
  "**Require well-founded progress.** Every step must close an arm or produce a strictly smaller named residual; merely renaming the obligation is not progress.",
  "**Prefer the cheapest currency.** Try direct constraint, contextual distinction and compression before charging or entropy when their prerequisites are present.",
  "**Keep currencies separate.** Deficiency, surplus, entropy, rank, boundary mass and concentration cannot pay one another without a proved interface.",
  "**Preserve every independent squeeze.** A repair must retain the strict demand-versus-supply slack used by each quantitative contradiction.",
  "**Do not launder an uncovered outcome.** If exhaustiveness is not proved on the retained fiber, retain the exact negation as a typed residual.",
  "**Check dependencies in the forward direction.** Every required invariant or theorem must be introduced before the step that consumes it.",
  "**Check the interface, not the label.** The consumer must accept exactly the witness, boundary data and preservation facts the move constructs.",
  "**Split on the first consumed hypothesis.** A split on the conclusion alone has no productive negative consumer; descend to the first local obligation instead.",
  "**Try all applicable minimality moves.** Deletion, contraction, replacement and refined orders each have distinct hypotheses; record which have actually been consumed.",
  "**Inventory before moving.** Select only after listing present, accounted and unaccounted structure together with technique prerequisites.",
  "**Relocation is not progress.** A peel, deferral or routing record needs a receiving consumer with certified capacity; otherwise it only re-encodes the same burden.",
  "**An unproved intermediate fact is a diamond, not a stop.** Its positive arm continues the move and its negative arm retains the first structured failure, subject to locality and progress.",
  "**Treat the recorded plan as binding.** A different object, move or reformulation is a plan repair and must be justified before work changes direction.",
  "**Failure certificates are not positive structure.** A hypothetical context, token or routing record says what one method did not establish; it does not create a path, cycle or carrier in the original object.",
  "**Do not re-prove settled input.** Use inherited facts as data; do not reapply an exhausted technique to the same observable or repair an upstream choice downstream.",
  "**Check prerequisites before targets.** A move selected for its target rows is inadmissible when its required disjointness, shared state, representative or boundedness is absent.",
  "**Compute finite tables before relying on them.** A table with surviving cases is useful only when its parameters, coverage and structural survivor consumer are proved."
] as const;

export const CLOSURE_CHECKLISTS = [
  { title: "Before touching a branch", source: "Branch setup", items: ["I have identified the first unsupported obligation rather than a downstream symptom.", "I have written the complete semantic region of the incoming branch: hypotheses, exclusions, active case and residual data.", "I have read the conjunction of facts as a whole.", "I have followed directed dependencies and declared requirements rather than inferred them from prose.", "I have checked whether an existing routed residual already carries the apparently missing information."] },
  { title: "Admitting a dichotomy", source: "Transition admission", items: ["The proposition is exact, quantified and about the retained object.", "It is not already recorded; if it is a conjunction, the first-failure split is ordered.", "The positive arm preserves the existing continuation and interface.", "The negative arm is typed by an object, witness, fiber, count or bound.", "Both arms have a productive consumer or a proved decreasing continuation.", "The transition is exhaustive and introduces no unproved global result."] },
  { title: "Closing a residual", source: "Move execution", items: ["The object is the complete residual as produced, not a projection or equivalent inequality.", "Every split passes refinement, exhaustiveness, locality and consumption.", "The currency and the structural register row consumed are named.", "Only branch-state facts, fixed inputs and textbook material are used.", "Every arm has a certificate or a strictly smaller typed residual.", "Every required witness is declared or constructed and proved on this branch.", "Charging has distinct demands, a total assignment, certified capacities and no double counting.", "Loops have an integer measure, strict decrease and invariant restoration.", "Compression proves context preservation and strict decrease before minimality is invoked.", "Exhaustive routing is proved on the retained fiber; otherwise the exact negation remains open.", "All independent quantitative inequalities retain their strict slack."] },
  { title: "Declaring a branch closed", source: "Closure verification", items: ["Every reachable terminal has a proved hit, defect, compression, capacity, rigidity, identification or complete enumeration certificate.", "No repeated exhausted move, object substitution, unconsumed outcome or child remains.", "The diagram, dependency record, invariant ledger and audit record agree.", "Every requirement is introduced before it is consumed.", "The formal proposition, carrier and execution result match the intended mathematical statement.", "Any weaker theorem before a remaining open branch is stated explicitly."] },
  { title: "Reopening an open branch", source: "Continuation", items: ["The producer’s exact residual and every inherited fact are copied without reformulation.", "The intended conclusion is expanded into constructions, preservation claims and cited lemmas.", "The first failed obligation is identified and its exact negation is retained.", "The retained object, interface and realization domain remain fixed unless transport is proved.", "The inventory and move history are updated before selecting a new technique.", "Every local lemma is on the queue with inputs, prerequisites, closing move and failure route.", "Full closure continues through every descendant and base case."] },
  { title: "Auditing an offered consumer", source: "Consumer audit", items: ["The consumer’s hypothesis is an exact bound on a named quantity.", "That quantity is traced to the branch ledger with a no-overcount identity.", "The branch’s forced lower bound and the consumer’s required upper bound are computed with strictness.", "If the consumer is unavailable, the inventory returns to the hypothesis whose failure produced the residual.", "Currencies are not mixed, and a candidate is selected from the inventory rather than from a diagnostic table alone."] }
] as const;

export const ARTIFACT_ROWS = [
  ["Proof graph", "Replace the unsupported transition by an exhaustive decision, preserve the positive continuation, append typed children, and give every terminal a consumer or certificate."],
  ["Diagram and state table", "Record each new state with its input, output, mathematical source and closure route."],
  ["Dependency record", "Name every requirement and the failure route for every arm so coverage is mechanically checkable."],
  ["Invariant ledger", "Record reusable facts with where introduced, where consumed and their role; keep namespaces distinct."],
  ["Lemma requirements", "List each local result and verify every requirement is established before use."],
  ["Resilience record", "State what survives if a closing lemma fails: the complete standing state plus the exact negation."],
  ["Monotonicity and budget tables", "Recheck deletion, replacement, peel, transfer and handoff preservation and all no-double-counting claims."],
  ["Formal audit", "Check the intended proposition, execution carrier, wiring, ancestry and kernel result independently."]
] as const;
