import type { ProofGraphDocument } from "./types";

/**
 * A tiny made-up proof, used to check that the explorer works on any document
 * rather than on one particular paper.
 *
 * The claim: an even number that is not twice an odd number is divisible by four.
 */
export const TEST_DOCUMENT: ProofGraphDocument = {
  id: "toy",
  title: "A toy dependency diagram",
  subtitle: "Six steps, used only in tests",
  slug: "toy",
  source: { files: ["toy-a.tex", "toy-b.tex"], diagramNodes: 6, figures: 2 },
  chapters: [
    {
      id: "one",
      title: "Splitting an even number",
      shortTitle: "Setup",
      description: "Fixes the number and splits on the parity of its half.",
      source: "toy-a.tex",
      prefix: "",
    },
    {
      id: "two",
      title: "The even case",
      shortTitle: "Even case",
      description: "Divides again and concludes.",
      source: "toy-b.tex",
      prefix: "",
    },
  ],
  macros: { "\\Evens": "\\mathcal E" },
  groups: [
    {
      id: "part-a",
      title: "Part A - setup",
      summary: "Fixes an even number and asks whether its half is odd.",
      caption: "Fix the number and split.",
      chapter: "one",
    },
    {
      id: "part-b",
      title: "Part B - the even case",
      summary: "Halves the number a second time and concludes.",
      caption: "Divide and repeat.",
      chapter: "two",
    },
  ],
  nodes: [
    {
      id: "1",
      number: "1",
      chapter: "one",
      label: "an integer $n\\in\\Evens$",
      shape: "assertion",
      group: "part-a",
      overview: "Fix an even integer.",
      aliases: [],
      blocks: [],
      itemRefs: ["def:even"],
      invariantRefs: ["one:1"],
      constantRefs: [],
      topics: ["Setup"],
    },
    {
      id: "2",
      number: "2",
      chapter: "one",
      label: "is $n/2$ odd?",
      shape: "decision",
      group: "part-a",
      overview: "Split on the parity of the half.",
      aliases: [],
      blocks: [],
      itemRefs: ["lem:halving"],
      invariantRefs: ["one:1"],
      constantRefs: [],
      topics: ["Parity split"],
    },
    {
      id: "3",
      number: "3",
      chapter: "one",
      label: "$n=2m$ with $m$ odd",
      shape: "terminal",
      group: "part-a",
      overview: "The excluded case.",
      aliases: [],
      blocks: [],
      itemRefs: [],
      invariantRefs: [],
      constantRefs: [],
      topics: [],
      dossier: {
        closingResult: "definition of an odd number",
        closingItems: ["def:even"],
        closingCondition: "$m\\equiv1\\pmod 2$",
        slack: "exact",
        redundantCover: "---",
        residualCounterexample: "None.",
      },
    },
    {
      id: "4",
      number: "4",
      chapter: "one",
      label: "$n/2$ is even; continued in Part B",
      shape: "assertion",
      group: "part-a",
      overview: "Pass the halved value onward.",
      aliases: ["5"],
      blocks: [],
      itemRefs: ["lem:halving"],
      invariantRefs: [],
      constantRefs: [],
      topics: [],
    },
    {
      id: "5",
      number: "5",
      chapter: "two",
      label: "$n/2$ is even",
      shape: "assertion",
      group: "part-b",
      overview: "Restatement in the second panel.",
      aliases: ["4"],
      blocks: [],
      itemRefs: [],
      invariantRefs: [],
      constantRefs: [],
      topics: [],
    },
    {
      id: "6",
      number: "6",
      chapter: "two",
      label: "$4\\mid n$",
      shape: "terminal",
      group: "part-b",
      overview: "The conclusion.",
      aliases: [],
      blocks: [],
      itemRefs: ["thm:toy"],
      invariantRefs: [],
      constantRefs: [],
      topics: ["Conclusion"],
    },
  ],
  edges: [
    { id: "e1", source: "1", target: "2", branch: null, kind: "flow" },
    { id: "e2", source: "2", target: "3", branch: "yes", kind: "flow" },
    { id: "e3", source: "2", target: "4", branch: "no", kind: "flow" },
    { id: "e4", source: "4", target: "5", branch: "continues in Part B", kind: "continuation" },
    { id: "e5", source: "5", target: "6", branch: null, kind: "flow" },
  ],
  items: [
    {
      key: "def:even",
      kind: "definition",
      title: "Even",
      statementLatex: "An integer $n$ is \\emph{even} when $n=2m$ for some integer $m$.",
      sourceLine: 10,
    },
    {
      key: "lem:halving",
      kind: "lemma",
      title: "Halving preserves integrality",
      statementLatex:
        "If $n$ is even, so that \\eqref{eq:halving} holds, then $n/2$ is an integer.",
      plain: "Halving an even number lands on an integer.",
      role: "Lets the argument recurse.",
      requires: "def:even",
      requiresItems: ["def:even"],
      sourceLine: 20,
    },
    {
      key: "thm:toy",
      kind: "theorem",
      title: "Divisibility by four",
      statementLatex: "\\[ 4 \\mid n \\]",
      plain: "The conclusion of the toy argument.",
      role: "Closes the branch.",
      sourceLine: 30,
    },
  ],
  equations: [
    {
      key: "eq:halving",
      number: 1,
      latex: "n = 2m",
      sourceLine: 12,
    },
  ],
  invariants: [
    {
      id: "one:1",
      number: 1,
      name: "Evenness",
      nodes: ["1", "2"],
      constraint: "$n\\equiv0\\pmod 2$",
      budget: "---",
      usedBy: ["lem:halving"],
    },
  ],
  constants: [
    {
      symbol: "$2$",
      value: "$2$",
      meaning: "the only even prime",
      establishedIn: ["def:even"],
    },
  ],
};
