import Hypostructure.Core.Prelude
import Hypostructure.Core.Problem
import Hypostructure.Core.Progress
import Hypostructure.Core.Context
import Hypostructure.Core.SemanticEquivalence
import Hypostructure.Core.Provision
import Hypostructure.Core.Coordinate.System
import Hypostructure.Core.Coordinate.Path
import Hypostructure.Core.Coordinate.Transport
import Hypostructure.Core.Assembly.Locality
import Hypostructure.Core.Assembly.AtomContext
import Hypostructure.Core.Assembly.LocalToGlobal
import Hypostructure.Core.Response.System
import Hypostructure.Core.Response.FiniteTable
import Hypostructure.Core.Response.SameInterface
import Hypostructure.Core.Budget.Resource
import Hypostructure.Core.Budget.Dynamic
import Hypostructure.Core.Budget.Work
import Hypostructure.Core.Budget.Transcript
import Hypostructure.Core.Finite.Enumeration
import Hypostructure.Core.Finite.Search
import Hypostructure.Core.Finite.Accounting
import Hypostructure.Core.Finite.Partition
import Hypostructure.Core.Finite.ConnectedPartition
import Hypostructure.Core.Finite.MaximalSelection
import Hypostructure.Core.Finite.EssentialCarrier
import Hypostructure.Core.Finite.CertifiedTableAggregation
import Hypostructure.Core.Finite.CertifiedTableBounds
import Hypostructure.Core.Finite.Flatten
import Hypostructure.Core.Finite.ScheduleEvents
import Hypostructure.Core.Finite.ColdCorridor
import Hypostructure.Core.Finite.ScheduleEventRoute
import Hypostructure.Core.Finite.ScaleRoute
import Hypostructure.Core.Finite.SelectedSchedule
import Hypostructure.Core.FiniteTriangle
import Hypostructure.Core.FiniteBitRelationBarrier
import Hypostructure.Core.DyadicLength
import Hypostructure.Core.Strategy.ExactFiniteLocalAlgebraBitTable
import Hypostructure.Core.OrderThresholdSplit
import Hypostructure.Core.ArithmeticTransport
import Hypostructure.Core.FiniteEntropy
import Hypostructure.Core.OneThreeRepair
import Hypostructure.Core.AffineBalance
import Hypostructure.Core.SupportSplit
import Hypostructure.Core.Degradation
import Hypostructure.Core.Residual.Ledger
import Hypostructure.Core.Residual.ExactLedger
import Hypostructure.Core.Residual.Stage
import Hypostructure.Core.Residual.Query
import Hypostructure.Core.Residual.Decision
import Hypostructure.Core.Residual.DecisionExhaustion
import Hypostructure.Core.Residual.Focus
import Hypostructure.Core.Residual.ProofProjection
import Hypostructure.Core.Residual.Join
import Hypostructure.Core.Compactness.Extraction
import Hypostructure.Core.ClosedLedger.Closure
import Hypostructure.Core.ClosedLedger.Quotient
import Hypostructure.Core.ClosedLedger.Propagation
import Hypostructure.Core.Execution
import Hypostructure.Core.Routing
import Hypostructure.Core.Closure
import Hypostructure.Core.Metadata
import Hypostructure.Core.Strategy
import Hypostructure.Core.Strategy.ExactExecution
import Hypostructure.Core.Strategy.ProblemResidual
import Hypostructure.Core.Strategy.FactOnlyStrategy
import Hypostructure.Core.Strategy.MinimalCounterexampleScope
import Hypostructure.Graph.Strategy.SpineVocabulary
import Hypostructure.Graph.Strategy.SpineRows
import Hypostructure.Graph.Strategy.SpineRun
import Hypostructure.Core.Strategy.FactManifest
import Hypostructure.Fixtures.ExactLedger
import Hypostructure.Fixtures.ExactExecution
import Hypostructure.Fixtures.MinimalCounterexampleScope
import Hypostructure.Fixtures.DerivedFactPublication
import Hypostructure.Fixtures.AutomaticLedgerClosure
import Hypostructure.Fixtures.ExactLedgerEmptinessClosure
import Hypostructure.Fixtures.LedgerAutorouting
import Hypostructure.Fixtures.BranchScopedExactLedger
import Hypostructure.Fixtures.ExactLedgerOpacity
import Hypostructure.Fixtures.ExactLedgerDuplicateFact
import Hypostructure.Fixtures.ExactLedgerMissingFact
import Hypostructure.Fixtures.ExactExecutionMissingRequirement
import Hypostructure.Fixtures.ExactExecutionDroppedFact
import Hypostructure.Core.Strategy.BinaryDecisionDichotomy
import Hypostructure.Core.Strategy.ColdBranchAggregation
import Hypostructure.Core.Strategy.AtomContextObstructionDichotomy
import Hypostructure.Core.Strategy.FiniteScheduleCapacity
import Hypostructure.Core.Strategy.ObstructionPackingClosure
import Hypostructure.Core.Strategy.ExactFiniteLocalAlgebra
import Hypostructure.Core.Strategy.OrderedSurplusActivation
import Hypostructure.Core.Strategy.BaselineDemandAccounting
import Hypostructure.Core.Strategy.CanonicalPairResponseAccounting
import Hypostructure.Core.Strategy.CanonicalCapacityTokenAccounting
import Hypostructure.Core.Strategy.CoupledHomogeneousFibrePressure
import Hypostructure.Core.EntropyPackingBudget
import Hypostructure.Graph.Strategy.ColdBranchPreludeAggregation
import Hypostructure.Core.NormalForm.ClassClosure
import Hypostructure.Core.NormalForm.SignGap
import Hypostructure.Core.NormalForm.EqualityRigidity
import Hypostructure.CT1.Automation
import Hypostructure.CT2.Automation
import Hypostructure.CT3.Automation
import Hypostructure.CT3.RunSchedule
import Hypostructure.CT3.Schedule
import Hypostructure.CT3.SameInterface
import Hypostructure.CT3.ScheduleWitness
import Hypostructure.CT3.ResidualRoute
import Hypostructure.CT4.Automation
import Hypostructure.CT5.Automation
import Hypostructure.CT6.Automation
import Hypostructure.CT7.Automation
import Hypostructure.CT8.Automation
import Hypostructure.CT9.Automation
import Hypostructure.CT10.Automation
import Hypostructure.CT11.Automation
import Hypostructure.CT12.Automation
import Hypostructure.CT13.Automation
import Hypostructure.CT14.Automation
import Hypostructure.CT15.Automation
import Hypostructure.CT16.Automation
import Hypostructure.CT17.Automation
import Hypostructure.CTAdapters
import Hypostructure.Routes.Registry
import Hypostructure.Routes.Accumulated
import Hypostructure.Graph.Object
import Hypostructure.Graph.Problem
import Hypostructure.Graph.Finite
import Hypostructure.Graph.FiniteEdgeBudget
import Hypostructure.Graph.SupportComponents
import Hypostructure.Graph.Strategy
import Hypostructure.Graph.SupportCharge
import Hypostructure.Graph.Budget
import Hypostructure.Graph.NegativeSupport
import Hypostructure.Graph.OneThreeRepair
import Hypostructure.Graph.Isomorphism
import Hypostructure.Graph.Induced
import Hypostructure.Graph.InducedPath
import Hypostructure.Graph.InducedPathMaximalPacking
import Hypostructure.Graph.PackedWindowRealization
import Hypostructure.Graph.External.HegdeSandeepShashank
import Hypostructure.Graph.Deletion
import Hypostructure.Graph.Progress
import Hypostructure.Graph.Minimality
import Hypostructure.Graph.DeletionCriticality
import Hypostructure.Graph.Target
import Hypostructure.Graph.MinimumDegreeCycleTarget
import Hypostructure.Graph.Coordinate
import Hypostructure.Graph.Boundary
import Hypostructure.Graph.Gluing
import Hypostructure.Graph.BoundariedAtom
import Hypostructure.Graph.AtomResponse
import Hypostructure.Graph.BoundaryOverlap
import Hypostructure.Graph.Replacement
import Hypostructure.Graph.Response
import Hypostructure.Graph.TargetClosure
import Hypostructure.Graph.CT1
import Hypostructure.Graph.CT2
import Hypostructure.Graph.CT3
import Hypostructure.Graph.CT4
import Hypostructure.Graph.CT5
import Hypostructure.Graph.CT6
import Hypostructure.Graph.CT7
import Hypostructure.Graph.CT8
import Hypostructure.Graph.CT9
import Hypostructure.Graph.CT10
import Hypostructure.Graph.CT11
import Hypostructure.Graph.CT12
import Hypostructure.Graph.CT13
import Hypostructure.Graph.CT14
import Hypostructure.Graph.CT15
import Hypostructure.Graph.CT16
import Hypostructure.Graph.CT17
import Hypostructure.Graph.RootedReturn
import Hypostructure.Graph.SkeletonBudget
import Hypostructure.Graph.SameTokenBlockerRoles
import Hypostructure.Graph.ReceiverLoad
import Hypostructure.Graph.ReceiverExhaustion
import Hypostructure.Graph.TargetDefectivePeel
import Hypostructure.Graph.DecoratedFan
import Hypostructure.Graph.TypeBOpenPorts
import Hypostructure.Graph.TypeBMarkedFan
import Hypostructure.Graph.TypeBFanClosedPorts
import Hypostructure.Graph.TypeBDegreeFour
import Hypostructure.Graph.TypeBHybridLedger
import Hypostructure.Graph.TypeBProfileSchedule
import Hypostructure.Graph.TypeBBridgeResidual
import Hypostructure.Graph.TypeBExclusion
import Hypostructure.Graph.TypeBFanMass
import Hypostructure.Graph.TypeBOverlapObstruction
import Hypostructure.Graph.TypeBPostLedgerCore
import Hypostructure.Graph.TypeBClosure
import Hypostructure.Graph.WindowCurvatureAlgebra
import Hypostructure.Graph.WindowCurvatureEnumeration
import Hypostructure.Graph.WindowCurvatureCode
import Hypostructure.Graph.WindowAttachmentLabel
import Hypostructure.Graph.NearCubicSpine
import Hypostructure.Graph.SurplusClasswiseOverload

-- Manuscript Part VIII--IX, Figures 8 and 9: the Type A receiver chain and the
-- route-8 carrier closure.  These are reached transitively by the Erdos-Gyarfas
-- application, but naming them here is what keeps a bare `lake build` covering
-- them -- `TypeARoute8Stages` in particular is imported by nothing else.
import Hypostructure.Graph.CutParity

-- Modules rescued from the quarantine boundary: legal modules that happened to
-- be reachable only through a quarantined one.  They are imported explicitly so
-- the quarantine removes the illegal carriers and nothing else -- without these
-- lines they would drop out of the build closure and silently stop being
-- checked.  See `quarantine.txt`.

import Hypostructure.Core.Contract
import Hypostructure.Core.Strategy.FiniteBarrierEnumeration
import Hypostructure.Core.Strategy.FiniteStateCapacityTheorems
import Hypostructure.Core.Strategy.MinimalSubobjectExclusion
import Hypostructure.Core.Strategy.Route8CarrierClosure
import Hypostructure.Core.Strategy.TargetAlgebraReduction
import Hypostructure.Core.Strategy.Validate
import Hypostructure.Graph.WedgeLowerBound

-- Rescued from the SequentialExtensionLedger quarantine boundary.
import Hypostructure.Graph.FinitePathSelection
import Hypostructure.Graph.Strategy.InterfaceReplacement
