import Hypostructure.Core.Coordinate.Transport
import Hypostructure.PDE.Representation

/-!
# PDE coordinate interfaces

Primitive coordinate families return realized maps.  They become primitives
of `Core.CoordinateSystem`; Core owns identity paths, composition, execution,
and composite transport.
-/

namespace Hypostructure.PDE

universe u

/-- A target-independent map between two represented local equations. -/
structure CoordinateMap (M : LocalModel.{u})
    (source target : M.atlas.Window) where
  transform : M.atlas.LocalObject source -> M.atlas.LocalObject target
  transformEquation : forall {object : M.atlas.LocalObject source},
    M.equation.EquationData source object ->
      M.equation.EquationData target (transform object)
  preservesEquation : forall {object : M.atlas.LocalObject source}
      (data : M.equation.EquationData source object),
    M.equation.satisfies data ->
      M.equation.satisfies (transformEquation data)

/-- A coordinate map together with its ambient realization. -/
structure RealizedCoordinate (M : LocalModel.{u})
    (source target : M.atlas.Window) extends CoordinateMap M source target where
  realize : M.problem.Ambient -> M.problem.Ambient
  realizes : forall G,
    transform (M.atlas.restrict G source) =
      M.atlas.restrict (realize G) target
  preservesBaseline : forall {G}, M.problem.Baseline G ->
    M.problem.Baseline (realize G)

/-- The Core coordinate system generated by PDE realized primitives. -/
def coordinateSystem (M : LocalModel.{u}) : Core.CoordinateSystem M.problem where
  Coordinate := M.atlas.Window
  Object := fun _ => M.problem.Ambient
  realize := fun _ object => object
  Primitive := fun source target => RealizedCoordinate M source target
  act := fun step object => step.realize object

/-- Primitive baseline laws registered once for Core path transport. -/
def primitiveBaselineTransport (M : LocalModel.{u}) :
    Core.PrimitiveBaselineTransport (coordinateSystem M) where
  preserves := fun step _ baseline => step.preservesBaseline baseline

/-- Restriction is the canonical realized coordinate for a nested window. -/
def restrictionCoordinate (M : LocalModel.{u}) {small large : M.atlas.Window}
    (h : M.atlas.nested small large) : RealizedCoordinate M large small where
  transform := M.atlas.restrictLocal h
  transformEquation := M.equation.restrictEquation h
  preservesEquation := M.equation.restrict_satisfies h
  realize := id
  realizes := fun G => M.atlas.restrict_global G h
  preservesBaseline := fun hG => hG

namespace EquationState

/--
Transport a represented equation state through one registered PDE
coordinate.  The local object, equation data, and validity proof are all
obtained from the same primitive coordinate; callers cannot supply any of
the three transported fields separately.
-/
def transportCoordinate {M : LocalModel.{u}}
    {source target : M.atlas.Window}
    (state : EquationState M.equation source)
    (coordinate : RealizedCoordinate M source target) :
    EquationState M.equation target where
  object := coordinate.transform state.object
  data := coordinate.transformEquation state.data
  valid := coordinate.preservesEquation state.data state.valid

/--
Transport a represented equation state through Core's coordinate path.
This is a lift of `Core.CoordinatePath`; it defines neither a second path
type nor a second coordinate executor.
-/
def transportPath {M : LocalModel.{u}}
    {source target : M.atlas.Window}
    (state : EquationState M.equation source)
    (path : Core.CoordinatePath (coordinateSystem M) source target) :
    EquationState M.equation target :=
  match path with
  | .nil => state
  | .cons step suffix =>
      (state.transportCoordinate step).transportPath suffix

@[simp]
theorem transportPath_nil {M : LocalModel.{u}}
    {window : M.atlas.Window}
    (state : EquationState M.equation window) :
    state.transportPath (Core.CoordinatePath.nil
      (C := coordinateSystem M)) = state :=
  rfl

@[simp]
theorem transportPath_cons {M : LocalModel.{u}}
    {source middle target : M.atlas.Window}
    (state : EquationState M.equation source)
    (step : RealizedCoordinate M source middle)
    (suffix :
      Core.CoordinatePath (coordinateSystem M) middle target) :
    state.transportPath (.cons step suffix) =
      (state.transportCoordinate step).transportPath suffix :=
  rfl

/-- Path append is exactly sequential represented-equation transport. -/
@[simp]
theorem transportPath_append {M : LocalModel.{u}}
    {source middle target : M.atlas.Window}
    (first : Core.CoordinatePath (coordinateSystem M) source middle)
    (state : EquationState M.equation source)
    (suffix : Core.CoordinatePath (coordinateSystem M) middle target) :
    state.transportPath (first.append suffix) =
      (state.transportPath first).transportPath suffix := by
  let motive := fun source middle
      (path : Core.CoordinatePath (coordinateSystem M) source middle) =>
    ∀ (sourceState : EquationState M.equation source)
      {target : M.atlas.Window}
      (suffix : Core.CoordinatePath (coordinateSystem M) middle target),
      sourceState.transportPath (path.append suffix) =
        (sourceState.transportPath path).transportPath suffix
  exact Core.CoordinatePath.recOn (motive := motive) first
    (by
      intro coordinate sourceState target suffix
      rfl)
    (by
      intro source middle endpoint step tail ih sourceState target suffix
      exact ih (sourceState.transportCoordinate step) suffix)
    state suffix

/-- Equation validity is inherited along every Core coordinate path. -/
theorem transportPath_valid {M : LocalModel.{u}}
    {source target : M.atlas.Window}
    (state : EquationState M.equation source)
    (path : Core.CoordinatePath (coordinateSystem M) source target) :
    M.equation.satisfies (state.transportPath path).data :=
  (state.transportPath path).valid

/--
If the source state is the restriction of an ambient object, its transported
local object is the restriction of Core's ambient `path.run`.  Thus local
equation transport and ambient coordinate execution cannot diverge.
-/
theorem transportPath_object_eq_restrict_run {M : LocalModel.{u}}
    {source target : M.atlas.Window}
    (path : Core.CoordinatePath (coordinateSystem M) source target)
    (state : EquationState M.equation source)
    (ambient : M.problem.Ambient)
    (source_eq : state.object = M.atlas.restrict ambient source) :
    (state.transportPath path).object =
      M.atlas.restrict (path.run ambient) target := by
  let motive := fun source target
      (path : Core.CoordinatePath (coordinateSystem M) source target) =>
    ∀ (sourceState : EquationState M.equation source)
      (sourceAmbient : M.problem.Ambient),
      sourceState.object = M.atlas.restrict sourceAmbient source →
        (sourceState.transportPath path).object =
          M.atlas.restrict (path.run sourceAmbient) target
  exact Core.CoordinatePath.recOn (motive := motive) path
    (by
      intro coordinate sourceState sourceAmbient sourceEq
      exact sourceEq)
    (by
      intro source middle endpoint step suffix ih sourceState sourceAmbient
        sourceEq
      exact ih (sourceState.transportCoordinate step)
        (step.realize sourceAmbient) (by
          change step.transform sourceState.object =
            M.atlas.restrict (step.realize sourceAmbient) _
          rw [sourceEq]
          exact step.realizes sourceAmbient))
    state ambient source_eq

end EquationState

/-- Optional family of recentering coordinates. -/
structure RecenteringInterface (M : LocalModel.{u}) where
  Shift : Type u
  targetWindow : Shift -> M.atlas.Window -> M.atlas.Window
  coordinate : forall (shift : Shift) (W : M.atlas.Window),
    RealizedCoordinate M W (targetWindow shift W)

/-- Optional family of rescaling coordinates.  Admissibility may be encoded in `Scale`. -/
structure RescalingInterface (M : LocalModel.{u}) where
  Scale : Type u
  targetWindow : Scale -> M.atlas.Window -> M.atlas.Window
  coordinate : forall (scale : Scale) (W : M.atlas.Window),
    RealizedCoordinate M W (targetWindow scale W)

namespace EquationState

/--
Restriction followed by recentering is precisely transport along the Core
path made from those two registered primitives.
-/
theorem transport_restriction_recenter {M : LocalModel.{u}}
    {source restricted : M.atlas.Window}
    (nested : M.atlas.nested restricted source)
    (recentering : RecenteringInterface M)
    (shift : recentering.Shift)
    (state : EquationState M.equation source) :
    state.transportPath
        (.cons (restrictionCoordinate M nested)
          (.cons (recentering.coordinate shift restricted) .nil)) =
      (state.restrict nested).transportCoordinate
        (recentering.coordinate shift restricted) :=
  rfl

end EquationState

/-- Optional normalization or gauge action compatible with representation semantics. -/
structure GaugeInterface (M : LocalModel.{u})
    (S : RepresentationSemantics M.problem) where
  Gauge : Type u
  coordinate : forall (_gauge : Gauge) (W : M.atlas.Window),
    RealizedCoordinate M W W
  equivalent_realize : forall (gauge : Gauge) (W : M.atlas.Window)
      (G : M.problem.Ambient),
    S.equivalent ((coordinate gauge W).realize G) G

/-- A quotient projection that identifies exactly the registered representations. -/
structure RepresentationQuotient (M : LocalModel.{u})
    (S : RepresentationSemantics M.problem) where
  Quotient : Type u
  project : M.problem.Ambient -> Quotient
  project_eq_iff : forall {G H}, project G = project H <-> S.equivalent G H

end Hypostructure.PDE
