import Hypostructure.PDE.NoSingularityTarget
import Hypostructure.PDE.Localization.ParabolicRecentering

/-!
# Change of frame, and the invariance it induces

The mirror of `Hypostructure/Graph/Isomorphism.lean`.  For graphs the ambient
symmetry is *graph isomorphism*: `FiniteObject.Isomorphic`, and
`IsomorphismInvariant` says a property does not distinguish isomorphic objects.
Every registered graph target is invariant, and that is what lets Core route
between presentations of the same graph.

For a local regularity problem the ambient symmetry is the **change of frame** a
localization actually performs: recentre on the singularity, then rescale
parabolically.  So `FrameChange` is a translation composed with the parabolic
scaling of `Localization/ParabolicRecentering.lean`, and `FrameInvariant` is the
exact analogue of `IsomorphismInvariant`.

The point of the module is `noSingularity_frameInvariant`: **the target does not
see the frame.**  Its proof is `RegularityTransport.singularSet_comp_affine` ---
the singular set moves *with* the frame --- so following a singular profile
across frames costs nothing, exactly as re-presenting a graph costs nothing.
That is the routing the framework owns on the graph side, translated.
-/

namespace Hypostructure.PDE

open MeasureTheory TopologicalSpace
open scoped ContDiff

universe v w

/-! ## The frame changes -/

/--
**A change of frame**: recentre by `shift`, after rescaling parabolically by
`scale`.  These are precisely the moves a parabolic localization makes, and the
only ones --- there is no rotation, because the heat operator's symmetry group
is generated by these two.
-/
structure FrameChange (dimension : ℕ) where
  /-- The parabolic scale.  Time carries its square; see `parabolicScaling`. -/
  scale : ℝ
  /-- Nondegeneracy, so the change is invertible. -/
  scale_ne_zero : scale ≠ 0
  /-- Where the new origin sits. -/
  shift : Place dimension

namespace FrameChange

variable {dimension : ℕ}

/-- The rescaling half, as a homeomorphism. -/
noncomputable def scaling (change : FrameChange dimension) :
    Place dimension ≃L[ℝ] Place dimension :=
  Localization.parabolicScaling change.scale_ne_zero

/-- **How a change of frame acts on a place.** -/
noncomputable def act (change : FrameChange dimension)
    (place : Place dimension) : Place dimension :=
  change.scaling place + change.shift

/-- The identity frame: unit scale, no shift. -/
def id (dimension : ℕ) : FrameChange dimension where
  scale := 1
  scale_ne_zero := one_ne_zero
  shift := 0

/-- **A change of frame reaches every place.**  The rescaling is a linear
homeomorphism and the recentring is a translation, so the composite is onto ---
which is why a window may be moved anywhere without losing anything. -/
theorem act_surjective (change : FrameChange dimension) :
    Function.Surjective change.act := fun target =>
  ⟨change.scaling.symm (target - change.shift), by simp [act]⟩

/-- The inverse move: undo the recentring, then the rescaling. -/
noncomputable def unact (change : FrameChange dimension)
    (place : Place dimension) : Place dimension :=
  change.scaling.symm (place - change.shift)

@[simp] theorem act_unact (change : FrameChange dimension)
    (place : Place dimension) : change.act (change.unact place) = place := by
  simp [act, unact]

@[simp] theorem unact_act (change : FrameChange dimension)
    (place : Place dimension) : change.unact (change.act place) = place := by
  simp [act, unact]

/-- **A change of frame preserves null sets**, in both directions.

`act` is an invertible linear map followed by a translation, so it carries the
ambient Haar measure to a nonzero multiple of itself.  This is what lets an
*almost everywhere* statement --- which is what interior regularity of a
distributional solution is --- be read in either frame. -/
theorem quasiMeasurePreserving_act (change : FrameChange dimension) :
    Measure.QuasiMeasurePreserving change.act
      (volume : Measure (Place dimension)) volume := by
  have determinant :
      LinearMap.det
          ((change.scaling : Place dimension →L[ℝ] Place dimension) :
            Place dimension →ₗ[ℝ] Place dimension) ≠ 0 :=
    (LinearEquiv.isUnit_det' change.scaling.toLinearEquiv).ne_zero
  have scaling : Measure.QuasiMeasurePreserving
      (fun place : Place dimension => change.scaling place) volume volume :=
    Measure.LinearMap.quasiMeasurePreserving volume _ determinant
  have shift : Measure.QuasiMeasurePreserving
      (fun place : Place dimension => place + change.shift) volume volume :=
    (measurePreserving_add_right volume change.shift).quasiMeasurePreserving
  exact shift.comp scaling

theorem quasiMeasurePreserving_unact (change : FrameChange dimension) :
    Measure.QuasiMeasurePreserving change.unact
      (volume : Measure (Place dimension)) volume := by
  have determinant :
      LinearMap.det
          ((change.scaling.symm : Place dimension →L[ℝ] Place dimension) :
            Place dimension →ₗ[ℝ] Place dimension) ≠ 0 :=
    (LinearEquiv.isUnit_det' change.scaling.symm.toLinearEquiv).ne_zero
  have scaling : Measure.QuasiMeasurePreserving
      (fun place : Place dimension => change.scaling.symm place) volume volume :=
    Measure.LinearMap.quasiMeasurePreserving volume _ determinant
  have shift : Measure.QuasiMeasurePreserving
      (fun place : Place dimension => place - change.shift) volume volume :=
    (measurePreserving_sub_right volume change.shift).quasiMeasurePreserving
  exact scaling.comp shift

end FrameChange

/-! ## Frame equivalence of objects -/

/--
**One object read in another's frame.**

`image` is `object` seen through `change`: its domain is the pullback of the
object's, and its field is the object's composed with the frame map.  Only the
field and the domain are constrained, because they are the only pieces the
regularity target speaks about.
-/
def FieldObject.ReadIn {dimension : ℕ} {Value : Type w}
    [NormedAddCommGroup Value] [NormedSpace ℝ Value]
    (change : FrameChange dimension)
    (object image : FieldObject dimension Value) : Prop :=
  (image.domain : Set (Place dimension)) =
      change.act ⁻¹' (object.domain : Set (Place dimension)) ∧
    image.field = fun place => object.field (change.act place)

/-- **Two objects are frame-equivalent** when some change of frame carries one
to the other.  The analogue of `FiniteObject.Isomorphic`. -/
def FieldObject.FrameEquivalent {dimension : ℕ} {Value : Type w}
    [NormedAddCommGroup Value] [NormedSpace ℝ Value]
    (object image : FieldObject dimension Value) : Prop :=
  ∃ change : FrameChange dimension, FieldObject.ReadIn change object image

/--
**A property that does not distinguish frames.**

The literal analogue of `Graph.FiniteObject.IsomorphismInvariant`, whose field
is `iff_of_iso : left.Isomorphic right → (Property left ↔ Property right)`.
-/
structure FieldObject.FrameInvariant {dimension : ℕ} {Value : Type w}
    [NormedAddCommGroup Value] [NormedSpace ℝ Value]
    (Property : FieldObject dimension Value → Prop) : Prop where
  iff_of_frame : ∀ {object image : FieldObject dimension Value},
    FieldObject.FrameEquivalent object image → (Property object ↔ Property image)

namespace FieldObject.FrameInvariant

variable {dimension : ℕ} {Value : Type w}
  [NormedAddCommGroup Value] [NormedSpace ℝ Value]
  {Property : FieldObject dimension Value → Prop}

/-- Transport a frame-invariant property across a change of frame.  Mirrors
`Graph.IsomorphismInvariant.transport`. -/
theorem transport (invariant : FieldObject.FrameInvariant Property)
    {object image : FieldObject dimension Value}
    (equivalent : FieldObject.FrameEquivalent object image) :
    Property object → Property image :=
  (invariant.iff_of_frame equivalent).mp

end FieldObject.FrameInvariant

/-! ## The target does not see the frame -/

/--
**The no-singularity target is frame-invariant.**

Both halves of the predicate move with the frame.  A representative smooth on
the domain composes with the affine change to one smooth on the moved domain
(`RegularityTransport.contDiffOn_affine_iff`), and the almost-everywhere
agreement transports because a change of frame preserves null sets
(`FrameChange.quasiMeasurePreserving_act`).  The inverse direction is the same
argument run through `FrameChange.unact`.

This is what makes "follow the singular profile" free: a strategy may recentre
and rescale as it likes, and the target it is trying to close is the same target
in every frame.
-/
theorem noSingularity_frameInvariant (dimension : ℕ) (Value : Type w)
    [NormedAddCommGroup Value] [NormedSpace ℝ Value] :
    FieldObject.FrameInvariant
      (fun object : FieldObject dimension Value =>
        NoSingularity (volume : Measure (Place dimension)) object) where
  iff_of_frame := by
    rintro object image ⟨change, domainEq, fieldEq⟩
    have unact_eq : change.unact =
        fun place => change.scaling.symm place +
          -(change.scaling.symm change.shift) := by
      funext place
      simp [FrameChange.unact, sub_eq_add_neg]
    constructor
    · rintro ⟨representative, smooth, agrees⟩
      refine ⟨fun place => representative (change.act place), ?_, ?_⟩
      · rw [domainEq]
        exact (Localization.RegularityTransport.contDiffOn_affine_iff
          (field := representative)
          (region := (object.domain : Set (Place dimension)))
          change.scaling change.shift).mpr smooth
      · filter_upwards [(change.quasiMeasurePreserving_act).ae agrees]
          with place inherited mem
        have moved : change.act place ∈ (object.domain : Set (Place dimension)) := by
          have := domainEq ▸ mem
          exact this
        rw [fieldEq]
        exact inherited moved
    · rintro ⟨representative, smooth, agrees⟩
      refine ⟨fun place => representative (change.unact place), ?_, ?_⟩
      · have preimage :
            ((fun place => change.scaling.symm place +
                -(change.scaling.symm change.shift)) ⁻¹'
              (image.domain : Set (Place dimension))) =
              (object.domain : Set (Place dimension)) := by
          rw [← unact_eq, domainEq]
          ext place
          simp [Set.mem_preimage]
        have transported := (Localization.RegularityTransport.contDiffOn_affine_iff
          (field := representative)
          (region := (image.domain : Set (Place dimension)))
          change.scaling.symm (-(change.scaling.symm change.shift))).mpr smooth
        rw [preimage] at transported
        simp only [unact_eq]
        exact transported
      · filter_upwards [(change.quasiMeasurePreserving_unact).ae agrees]
          with place inherited mem
        have moved : change.unact place ∈ (image.domain : Set (Place dimension)) := by
          rw [domainEq]
          simpa using mem
        have value := inherited moved
        rw [fieldEq] at value
        simpa using value

/-! ## The registered interface -/

/--
**The target interface of a local regularity problem.**

Mirrors `Graph.TargetInterface`, whose single field is the isomorphism
invariance of the target.  Here it is frame invariance.  The name is
`FrameTargetInterface` because `PDE.TargetInterface` is already taken by the
*observable* interface of `PDE/Target.lean`, which is a different notion.
-/
structure FrameTargetInterface {dimension : ℕ} {Value : Type w}
    [NormedAddCommGroup Value] [NormedSpace ℝ Value]
    (Target : FieldObject dimension Value → Prop) : Prop where
  /-- The registered target does not distinguish frames. -/
  frameInvariant : FieldObject.FrameInvariant Target

/-- The no-singularity target, registered with its interface.  Mirrors
`Graph.cycleTargetInterface`. -/
theorem noSingularityTargetInterface (dimension : ℕ) (Value : Type w)
    [NormedAddCommGroup Value] [NormedSpace ℝ Value] :
    FrameTargetInterface (fun object : FieldObject dimension Value =>
      NoSingularity (volume : Measure (Place dimension)) object) where
  frameInvariant := noSingularity_frameInvariant dimension Value

end Hypostructure.PDE
