import Mathlib.Data.Finset.Lattice.Fold
import Mathlib.Data.Fintype.Basic
import Mathlib.Tactic.DeriveFintype

/-!
# The declared response-coordinate signature

`def:declared-coordinate-signature`, verbatim in structure.

> The response-coordinate signature used in the proof is fixed once and for all.
> For a `T`-boundaried support `X`, a declared coordinate is a tuple
> `(k, ι, supp_X(r), val_X(r))`, where `k` is its kind, `ι` is its label,
> `supp_X(r)` is a finite set of vertices, edges, boundary incidences, paths, or
> windows of `X`, and `val_X(r)` is the corresponding value in the embedded
> support.  The declared coordinates are generated by the following clauses.
> (D1) boundary-degree entries at labelled boundary vertices; (D2) edge-rooted
> return data, completion-port data, first-entry receivers, connector lengths,
> receiver-entry channels, and the corresponding Mersenne return tests;
> (D3) induced-`P₁₃` window labels, legal-label relations, packed-window
> incidences, and cross-window incidence data; (D4) raw curvature coordinates
> indexed by internal length-two wedges; (D5) Type A trace data; (D6) Type B fan
> and bridge data; (D7) sparse surplus data: selected surplus ports, canonical
> port returns, open-port suppression paths, triangular-port response triangles,
> and sparse surplus-pair response coordinates; (D8) finite products, labelled
> copies, restrictions, and quotient images of coordinates already generated in
> clauses (D1)--(D7), with support equal to the union of the supports of the
> entries used.
>
> No other local response coordinate is available to a quotient.

Two things are formalized, and they are the two the manuscript uses downstream.

*The generation is closed.*  `Coordinate` is an inductive with one constructor
per generation clause: a base constructor carrying the kind, the label and the
finite support of clauses (D1)--(D7), and the four (D8) closure constructors.
"No other local response coordinate is available" is exactly the statement that
this inductive has no further constructors, so it is carried by the type rather
than asserted about it.

*The support of a derived coordinate is the union of the supports used.*  That
is `Coordinate.support` and the four equations below it.

The items a support is drawn from -- "vertices, edges, boundary incidences,
paths, or windows of `X`" -- and the label alphabet are parameters.  Clauses
(D1)--(D7) name families defined elsewhere in the manuscript; what the signature
contributes about them is their kind, their label and their support, which is
what every later definition reads off a declared coordinate.
-/

namespace Hypostructure.Graph.DeclaredSignature

universe u v

/-- The kind `k` of a declared coordinate: the generating clause it comes from.
Clauses (D1)--(D7) are the seven base kinds; (D8) is closure and adds no kind. -/
inductive Kind
  /-- (D1) boundary-degree entries at labelled boundary vertices. -/
  | boundaryDegree
  /-- (D2) edge-rooted return data, completion ports, first-entry receivers,
  connector lengths, receiver-entry channels, and Mersenne return tests. -/
  | returnData
  /-- (D3) induced-`P₁₃` window labels, legal-label relations, packed-window
  incidences, and cross-window incidence data. -/
  | windowLabel
  /-- (D4) raw curvature coordinates indexed by internal length-two wedges. -/
  | rawCurvature
  /-- (D5) Type A trace data. -/
  | typeATrace
  /-- (D6) Type B fan and bridge data. -/
  | typeBFan
  /-- (D7) sparse surplus data: selected surplus ports, canonical port returns,
  open-port suppression paths, triangular-port response triangles, and sparse
  surplus-pair response coordinates. -/
  | sparseSurplus
deriving DecidableEq, Fintype, Repr

/-- **A declared coordinate on a `T`-boundaried support.**

`base` is clauses (D1)--(D7): a kind, a label, and the finite support
`supp_X(r)`.  The remaining four constructors are clause (D8), the closure
under finite products, labelled copies, restrictions and quotient images.  The
type has no other constructor, which is the signature's closing sentence. -/
inductive Coordinate (Item : Type u) (Label : Type v) where
  /-- Clauses (D1)--(D7). -/
  | base (kind : Kind) (label : Label) (support : Finset Item)
  /-- (D8) a finite product of coordinates already generated. -/
  | product (left right : Coordinate Item Label)
  /-- (D8) a labelled copy of a coordinate already generated. -/
  | copy (label : Label) (source : Coordinate Item Label)
  /-- (D8) a restriction of a coordinate already generated. -/
  | restrict (source : Coordinate Item Label) (region : Finset Item)
  /-- (D8) a quotient image of a coordinate already generated. -/
  | quotientImage (source : Coordinate Item Label)

namespace Coordinate

variable {Item : Type u} {Label : Type v} [DecidableEq Item]

/-- **`supp_X(r)`.**  Clause (D8)'s "with support equal to the union of the
supports of the entries used" is the `product` equation; a labelled copy and a
quotient image reuse the support they were generated from, and a restriction
meets it with the region restricted to. -/
def support : Coordinate Item Label → Finset Item
  | .base _ _ items => items
  | .product left right => left.support ∪ right.support
  | .copy _ source => source.support
  | .restrict source region => source.support ∩ region
  | .quotientImage source => source.support

@[simp] theorem support_base (kind : Kind) (label : Label) (items : Finset Item) :
    (base kind label items : Coordinate Item Label).support = items := rfl

@[simp] theorem support_product (left right : Coordinate Item Label) :
    (product left right).support = left.support ∪ right.support := rfl

@[simp] theorem support_copy (label : Label) (source : Coordinate Item Label) :
    (copy label source).support = source.support := rfl

@[simp] theorem support_restrict (source : Coordinate Item Label)
    (region : Finset Item) :
    (restrict source region).support = source.support ∩ region := rfl

@[simp] theorem support_quotientImage (source : Coordinate Item Label) :
    (quotientImage source).support = source.support := rfl

/-- A restriction never leaves the support it restricts. -/
theorem support_restrict_subset (source : Coordinate Item Label)
    (region : Finset Item) :
    (restrict source region).support ⊆ source.support :=
  Finset.inter_subset_left

/-- Both entries of a product lie inside the product's support: this is the
sense in which a (D8) coordinate "uses" the entries it was generated from. -/
theorem support_subset_product_left (left right : Coordinate Item Label) :
    left.support ⊆ (product left right).support :=
  Finset.subset_union_left

theorem support_subset_product_right (left right : Coordinate Item Label) :
    right.support ⊆ (product left right).support :=
  Finset.subset_union_right

end Coordinate

end Hypostructure.Graph.DeclaredSignature
