import Hypostructure.Graph.ExitFourPeeling
import Hypostructure.Graph.BoundariedAtom
import Hypostructure.Graph.Response
import Hypostructure.Graph.Route8Carrier

/-!
# The canonical exit-`(4)` quotient family at a receiver

`def:typeA-exit4-family` fixes, at a saturated receiver `w`, a family
`𝒬₄(w)` of *boundary-degree-preserving response quotients* generated by five
canonical constructions -- the visible receiver-entry identifications, the
silent/excess basin quotient, the trace-local non-carrier quotient, the
continuation/cubic-switch quotient, and the two-carrier carrier-deletion
quotient -- and says:

> Exit (4) occurs precisely when one of these listed canonical quotients is
> target-defective.

The declared routed-load support is part of the canonical construction; the
definition lists it clause by clause, and in every clause it is *the routed
loads whose declared coordinate the quotient identifies or forgets*.  That is
the reading taken here, so the clause-by-clause list is derived from the
quotient rather than asserted alongside it.

`def:typeA-exit4-peeling` then defines an *exit-(4) witness for a routed load*
`u`: a quotient `q ∈ 𝒬₄(w)`, two realizations in the same boundary-degree
fibre, a compatible outside context distinguishing their target predicates, and
the requirement that the declared support of `q` contains the canonical
coordinate of `u`.  `Witness` below records exactly that generated
target-defective family member, the same-boundary realizations, and the routed
load whose canonical coordinate it supports.  The charge-descent and loop
termination statements belong to the separate peeling ledger in
`ExitFourPeeling`; this file only defines the canonical family datum consumed by
the node `[101]` decision.

Nothing here knows a graph family, a manuscript node, a threshold, or a proof:
the family is quantified over its target predicate, its reading, its carrier
universe, and the canonical generation predicate its clauses supply.
-/

namespace Hypostructure.Graph.ExitFour

open Hypostructure

universe u

/-- **The five generating constructions of `def:typeA-exit4-family`.**

A member of `𝒬₄(w)` records which construction generated it; the mathematical
content the exit consumes -- target-defectiveness and the declared routed-load
support -- is the same for all five, exactly as `lem:typeA-exit4-discharge`
uses them.  The route-8-only carrier-deletion construction is present in the
common clause vocabulary, but no pre-route row generates it; it can appear only
after the selected exit-`(8)` ledger residual supplies the Part IX carrier
deletion facts. -/
inductive ReceiverClause where
  /-- (Q1): the visible receiver-entry coordinate identifications. -/
  | visibleEntry
  /-- (Q2): the silent/excess boundary-response quotient of the basin `B(w)`. -/
  | silentBasin
  /-- (Q3): the trace-local non-carrier quotient of a trace basin. -/
  | traceBasin
  /-- (Q4): the finite continuation or cubic-switch quotient. -/
  | continuationSwitch
  /-- (Q5): the two-carrier carrier-deletion quotient, available only in the
  route-`8` branch after the selected indexed entry has been committed. -/
  | carrierDeletion
  deriving DecidableEq, Repr

/-- **`𝒬₄(w)`**, at a receiver of a support.

`entry` is the receiver's declared reading: a finite family of declared
coordinates, each with the carrier support its declared support uses, presented
on one labelled boundary.  `coordinate` is the canonical coordinate a routed
load is given by `def:declared-coordinate-signature`, and `Generated` is the
family's own generation predicate: `Generated clause base identified` says the
listed construction `clause` generates, from the reading `base`, the quotient
that identifies or forgets exactly `identified`.

No construction is generated here.  A node that owns one of the five clauses
supplies it through `Generated`; every statement below is quantified over the
family, so no row invents a member and none is dropped. -/
structure ReceiverFamily (Target : FiniteObject.{u} → Prop) {object : FiniteObject.{u}}
    (support : Finset object.Vertex) (threshold : Nat)
    (receiver : object.Vertex) (Carrier : Type u) where
  /-- The receiver's declared reading, on one labelled boundary. -/
  entry : Route8.Entry Target Carrier
  /-- The canonical declared coordinate of a routed load. -/
  coordinate : object.Vertex → entry.Coordinate
  /-- Every routed load's canonical coordinate is declared by the reading. -/
  coordinate_declared : ∀ load ∈ object.routedLoads support threshold receiver,
    coordinate load ∈ entry.coordinates
  /-- The generation predicate of the five canonical constructions. -/
  Generated : ReceiverClause → Finset entry.Coordinate → Finset entry.Coordinate → Prop
  /-- A generated quotient is taken on a declared reading. -/
  generated_base : ∀ {clause base identified}, Generated clause base identified →
    base ⊆ entry.coordinates
  /-- A generated quotient identifies or forgets declared coordinates of the
  reading it is taken on. -/
  generated_identified : ∀ {clause base identified},
    Generated clause base identified → identified ⊆ base

namespace ReceiverFamily

variable {Target : FiniteObject.{u} → Prop} {object : FiniteObject.{u}}
variable {support : Finset object.Vertex} {threshold scale : Nat}
variable {receiver : object.Vertex} {Carrier : Type u}
variable (family : ReceiverFamily Target support threshold receiver Carrier)

attribute [local instance] vertexDecEq

/-- **The declared routed-load support of a member**: the routed loads whose
canonical declared coordinate the quotient identifies or forgets.  This is
`def:typeA-exit4-family`'s clause-by-clause list, read uniformly -- (Q1)'s
identified visible coordinates, (Q2)'s basin loads, (Q3)'s trace load, (Q4)'s
connector family, (Q5)'s indexed load. -/
noncomputable def declaredLoads
    (identified : Finset family.entry.Coordinate) : Finset object.Vertex :=
  letI : DecidablePred fun load : object.Vertex =>
      family.coordinate load ∈ identified :=
    fun _ => Classical.propDecidable _
  (object.routedLoads support threshold receiver).filter fun load =>
    family.coordinate load ∈ identified

theorem mem_declaredLoads {identified : Finset family.entry.Coordinate}
    {load : object.Vertex} :
    load ∈ family.declaredLoads identified ↔
      load ∈ object.routedLoads support threshold receiver ∧
        family.coordinate load ∈ identified := by
  letI : DecidablePred fun load : object.Vertex =>
      family.coordinate load ∈ identified :=
    fun _ => Classical.propDecidable _
  simp [declaredLoads]

theorem declaredLoads_subset (identified : Finset family.entry.Coordinate) :
    family.declaredLoads identified ⊆
      object.routedLoads support threshold receiver := by
  intro load member
  exact (family.mem_declaredLoads.mp member).1

end ReceiverFamily

/-- **An exit-`(4)` witness for one unpeeled routed load.**

This is the formal content of `def:typeA-exit4-peeling`: a generated member of
the canonical receiver family, a load whose declared coordinate is in that
member's support, two realizations in the same boundary-degree fibre, and a
compatible outside context distinguishing their target predicates. -/
structure Witness (Target : FiniteObject.{u} → Prop)
    {object : FiniteObject.{u}} (support : Finset object.Vertex)
    (threshold : Nat) (receiver : object.Vertex)
    (peeled : Finset object.Vertex) where
  Carrier : Type u
  family : ReceiverFamily Target support threshold receiver Carrier
  clause : ReceiverClause
  base : Finset family.entry.Coordinate
  identified : Finset family.entry.Coordinate
  generated : family.Generated clause base identified
  load : object.Vertex
  unpeeled : load ∈ unpeeledLoads support threshold receiver peeled
  declared : load ∈ family.declaredLoads identified
  boundary : Boundary
  left : BoundaryPiece boundary
  right : BoundaryPiece boundary
  sameBoundaryProfile : left.boundaryDegreeProfile = right.boundaryDegreeProfile
  targetDefect : Response.TargetDefect Target left right

namespace Witness

variable {Target : FiniteObject.{u} → Prop} {object : FiniteObject.{u}}
variable {support : Finset object.Vertex} {threshold : Nat}
variable {receiver : object.Vertex} {peeled : Finset object.Vertex}
variable {Carrier : Type u}

/-- A generated route-`8` carrier-deletion quotient with a target-defect is an
ordinary exit-`(4)` witness at the same selected receiver.  This is the generic
constructor used by Part IX after the ledger has already committed the selected
two-carrier entry and its declared deletion witness. -/
def of_carrierDeletion
    (family : ReceiverFamily Target support threshold receiver Carrier)
    {base identified : Finset family.entry.Coordinate}
    (generated :
      family.Generated ReceiverClause.carrierDeletion base identified)
    {load : object.Vertex}
    (unpeeled : load ∈ unpeeledLoads support threshold receiver peeled)
    (declared : load ∈ family.declaredLoads identified)
    {boundary : Boundary} {left right : BoundaryPiece boundary}
    (sameBoundaryProfile :
      left.boundaryDegreeProfile = right.boundaryDegreeProfile)
    (targetDefect : Response.TargetDefect Target left right) :
    Witness Target support threshold receiver peeled where
  Carrier := Carrier
  family := family
  clause := ReceiverClause.carrierDeletion
  base := base
  identified := identified
  generated := generated
  load := load
  unpeeled := unpeeled
  declared := declared
  boundary := boundary
  left := left
  right := right
  sameBoundaryProfile := sameBoundaryProfile
  targetDefect := targetDefect

/-- A committed no-exit-`(4)` fact is incompatible with a target-defective Q5
carrier-deletion quotient supporting a load in its recorded domain.  The domain
predicate is supplied by the ledger branch: in the silent route-`8` arm it is
the selected unpaid silent residual set. -/
theorem carrierDeletion_contradicts_noExitFour
    {eligible : object.Vertex → Prop}
    (noExitFour :
      ¬ ∃ witness : Witness Target support threshold receiver peeled,
        eligible witness.load)
    (family : ReceiverFamily Target support threshold receiver Carrier)
    {base identified : Finset family.entry.Coordinate}
    (generated :
      family.Generated ReceiverClause.carrierDeletion base identified)
    {load : object.Vertex}
    (unpeeled : load ∈ unpeeledLoads support threshold receiver peeled)
    (declared : load ∈ family.declaredLoads identified)
    (eligibleLoad : eligible load)
    {boundary : Boundary} {left right : BoundaryPiece boundary}
    (sameBoundaryProfile :
      left.boundaryDegreeProfile = right.boundaryDegreeProfile)
    (targetDefect : Response.TargetDefect Target left right) :
    False :=
  noExitFour ⟨of_carrierDeletion family generated unpeeled declared
    sameBoundaryProfile targetDefect, eligibleLoad⟩

attribute [local instance] vertexDecEq

theorem routed
    (witness : Witness Target support threshold receiver peeled) :
    witness.load ∈ object.routedLoads support threshold receiver :=
  ((mem_unpeeledLoads (object := object) support threshold receiver).mp
    witness.unpeeled).1

theorem fresh
    (witness : Witness Target support threshold receiver peeled) :
    witness.load ∉ peeled :=
  ((mem_unpeeledLoads (object := object) support threshold receiver).mp
    witness.unpeeled).2

/-- The peeling set after charging this exit-`(4)` witness. -/
noncomputable def nextPeeled
    (witness : Witness Target support threshold receiver peeled) :
    Finset object.Vertex :=
  Finset.cons witness.load peeled witness.fresh

theorem nextPeeled_subset_routedLoads
    (witness : Witness Target support threshold receiver peeled)
    (inside : peeled ⊆ object.routedLoads support threshold receiver) :
    witness.nextPeeled ⊆ object.routedLoads support threshold receiver := by
  intro vertex member
  simp [nextPeeled] at member
  rcases member with rfl | member
  · exact witness.routed
  · exact inside member

theorem residualLoad_nextPeeled
    (witness : Witness Target support threshold receiver peeled) :
    residualLoad support threshold receiver witness.nextPeeled + 1 =
      residualLoad support threshold receiver peeled := by
  classical
  simpa [nextPeeled] using
    residualLoad_insert support threshold receiver witness.unpeeled

end Witness

end Hypostructure.Graph.ExitFour
