import Hypostructure.Graph.ExitFourPeeling
import Hypostructure.Graph.BoundariedAtom
import Hypostructure.Graph.Response

/-!
# The canonical exit-`(4)` quotient family at a receiver

`def:typeA-exit4-family` fixes, at a saturated receiver `w`, a family
`𝒬₄(w)` of *boundary-degree-preserving response quotients* generated by five
canonical constructions -- the visible receiver-entry identifications, the
silent/excess basin quotient, the trace-local non-carrier quotient, the
continuation/cubic-switch quotient, and the two-carrier carrier-deletion
quotient -- and says:

> Exit (4) occurs precisely when one of these listed canonical quotients is
> target-defective.

The declared routed-load support is part of the canonical construction; the
definition lists it clause by clause, and in every clause it is *the routed
loads whose declared coordinate the quotient identifies or forgets*.  That is
the reading taken here, so the clause-by-clause list is derived from the
quotient rather than asserted alongside it.

`def:typeA-exit4-peeling` then defines an *exit-(4) witness for a routed load*
`u`: a quotient `q ∈ 𝒬₄(w)`, two realizations in the same boundary-degree
fibre, a compatible outside context distinguishing their target predicates, and
the requirement that the declared support of `q` contains the canonical
coordinate of `u`.  `Witness` below records exactly that generated
target-defective family member, the same-boundary realizations, and the routed
load whose canonical coordinate it supports.  The charge-descent and loop
termination statements belong to the separate peeling ledger in
`ExitFourPeeling`; this file only defines the canonical family datum consumed by
the node `[101]` decision.

Nothing here knows a graph family, a manuscript node, a threshold, a carrier
ledger, or a proof: the family is quantified over its target predicate, its
declared coordinate type, and the canonical generation predicate its clauses
supply.
-/

namespace Hypostructure.Graph.ExitFour

open Hypostructure

universe u

/-- **The five generating constructions of `def:typeA-exit4-family`.**

A member of `𝒬₄(w)` records which construction generated it; the mathematical
content the exit consumes -- target-defectiveness and the declared routed-load
support -- is the same for all five, exactly as `lem:typeA-exit4-discharge`
uses them.  The route-8-only carrier-deletion construction is present in the
common clause vocabulary, but no pre-route row generates it; it can appear only
after the selected exit-`(8)` ledger residual supplies the Part IX carrier
deletion facts. -/
inductive ReceiverClause where
  /-- (Q1): the visible receiver-entry coordinate identifications. -/
  | visibleEntry
  /-- (Q2): the silent/excess boundary-response quotient of the basin `B(w)`. -/
  | silentBasin
  /-- (Q3): the trace-local non-carrier quotient of a trace basin. -/
  | traceBasin
  /-- (Q4): the finite continuation or cubic-switch quotient. -/
  | continuationSwitch
  /-- (Q5): the two-carrier carrier-deletion quotient, available only in the
  route-`8` branch after the selected indexed entry has been committed. -/
  | carrierDeletion
  deriving DecidableEq, Repr

/-- **`𝒬₄(w)`**, at a receiver of a support.

`Coordinate` and `coordinates` are the receiver's declared reading. `coordinate`
is the canonical coordinate a routed load is given by
`def:declared-coordinate-signature`, and `Generated` is the family's own
generation predicate: `Generated clause base identified` says the listed
construction `clause` generates, from the reading `base`, the quotient that
identifies or forgets exactly `identified`.

No construction is generated here.  A node that owns one of the five clauses
supplies it through `Generated`; every statement below is quantified over the
family, so no row invents a member and none is dropped. -/
structure ReceiverFamily (Target : FiniteObject.{u} → Prop)
    {object : FiniteObject.{u}} (support : Finset object.Vertex)
    (threshold : Nat) (receiver : object.Vertex) where
  /-- The declared coordinate index of the receiver reading. -/
  Coordinate : Type u
  /-- Decidable equality on declared coordinates. -/
  coordinateDecEq : DecidableEq Coordinate
  /-- The declared coordinates of the receiver reading. -/
  coordinates : Finset Coordinate
  /-- The canonical declared coordinate of a routed load. -/
  coordinate : object.Vertex → Coordinate
  /-- Every routed load's canonical coordinate is declared by the reading. -/
  coordinate_declared : ∀ load ∈ object.routedLoads support threshold receiver,
    coordinate load ∈ coordinates
  /-- The generation predicate of the five canonical constructions. -/
  Generated : ReceiverClause → Finset Coordinate → Finset Coordinate → Prop
  /-- A generated quotient is taken on a declared reading. -/
  generated_base : ∀ {clause base identified}, Generated clause base identified →
    base ⊆ coordinates
  /-- A generated quotient identifies or forgets declared coordinates of the
  reading it is taken on. -/
  generated_identified : ∀ {clause base identified},
    Generated clause base identified → identified ⊆ base

namespace ReceiverFamily

variable {Target : FiniteObject.{u} → Prop} {object : FiniteObject.{u}}
variable {support : Finset object.Vertex} {threshold scale : Nat}
variable {receiver : object.Vertex}
variable (family : ReceiverFamily Target support threshold receiver)

attribute [local instance] vertexDecEq
attribute [local instance] ReceiverFamily.coordinateDecEq

/-- **The declared routed-load support of a member**: the routed loads whose
canonical declared coordinate the quotient identifies or forgets.  This is
`def:typeA-exit4-family`'s clause-by-clause list, read uniformly -- (Q1)'s
identified visible coordinates, (Q2)'s basin loads, (Q3)'s trace load, (Q4)'s
connector family, (Q5)'s indexed load. -/
noncomputable def declaredLoads
    (identified : Finset family.Coordinate) : Finset object.Vertex :=
  letI : DecidablePred fun load : object.Vertex =>
      family.coordinate load ∈ identified :=
    fun _ => Classical.propDecidable _
  (object.routedLoads support threshold receiver).filter fun load =>
    family.coordinate load ∈ identified

theorem mem_declaredLoads {identified : Finset family.Coordinate}
    {load : object.Vertex} :
    load ∈ family.declaredLoads identified ↔
      load ∈ object.routedLoads support threshold receiver ∧
        family.coordinate load ∈ identified := by
  letI : DecidablePred fun load : object.Vertex =>
      family.coordinate load ∈ identified :=
    fun _ => Classical.propDecidable _
  simp [declaredLoads]

theorem declaredLoads_subset (identified : Finset family.Coordinate) :
    family.declaredLoads identified ⊆
      object.routedLoads support threshold receiver := by
  intro load member
  exact (family.mem_declaredLoads.mp member).1

end ReceiverFamily

/-- **An exit-`(4)` witness for one unpeeled routed load.**

This is the formal content of `def:typeA-exit4-peeling`: a generated member of
the canonical receiver family, a load whose declared coordinate is in that
member's support, two realizations in the same boundary-degree fibre, and a
compatible outside context distinguishing their target predicates. -/
structure Witness (Target : FiniteObject.{u} → Prop)
    {object : FiniteObject.{u}} (support : Finset object.Vertex)
    (threshold : Nat) (receiver : object.Vertex)
    (peeled : Finset object.Vertex) where
  family : ReceiverFamily Target support threshold receiver
  clause : ReceiverClause
  base : Finset family.Coordinate
  identified : Finset family.Coordinate
  generated : family.Generated clause base identified
  load : object.Vertex
  unpeeled : load ∈ unpeeledLoads support threshold receiver peeled
  declared : load ∈ family.declaredLoads identified
  boundary : Boundary
  left : BoundaryPiece boundary
  right : BoundaryPiece boundary
  sameBoundaryProfile : left.boundaryDegreeProfile = right.boundaryDegreeProfile
  targetDefect : Response.TargetDefect Target left right

namespace Witness

variable {Target : FiniteObject.{u} → Prop} {object : FiniteObject.{u}}
variable {support : Finset object.Vertex} {threshold : Nat}
variable {receiver : object.Vertex} {peeled : Finset object.Vertex}

/-- A generated route-`8` carrier-deletion quotient with a target-defect is an
ordinary exit-`(4)` witness at the same selected receiver.  This is the generic
constructor used by Part IX after the ledger has already committed the selected
two-carrier entry and its declared deletion witness. -/
def of_carrierDeletion
    (family : ReceiverFamily Target support threshold receiver)
    {base identified : Finset family.Coordinate}
    (generated :
      family.Generated ReceiverClause.carrierDeletion base identified)
    {load : object.Vertex}
    (unpeeled : load ∈ unpeeledLoads support threshold receiver peeled)
    (declared : load ∈ family.declaredLoads identified)
    {boundary : Boundary} {left right : BoundaryPiece boundary}
    (sameBoundaryProfile :
      left.boundaryDegreeProfile = right.boundaryDegreeProfile)
    (targetDefect : Response.TargetDefect Target left right) :
    Witness Target support threshold receiver peeled where
  family := family
  clause := ReceiverClause.carrierDeletion
  base := base
  identified := identified
  generated := generated
  load := load
  unpeeled := unpeeled
  declared := declared
  boundary := boundary
  left := left
  right := right
  sameBoundaryProfile := sameBoundaryProfile
  targetDefect := targetDefect

/-- A committed no-exit-`(4)` fact is incompatible with a target-defective Q5
carrier-deletion quotient supporting a load in its recorded domain.  The domain
predicate is supplied by the ledger branch: in the silent route-`8` arm it is
the selected unpaid silent residual set. -/
theorem carrierDeletion_contradicts_noExitFour
    {eligible : object.Vertex → Prop}
    (noExitFour :
      ¬ ∃ witness : Witness Target support threshold receiver peeled,
        eligible witness.load)
    (family : ReceiverFamily Target support threshold receiver)
    {base identified : Finset family.Coordinate}
    (generated :
      family.Generated ReceiverClause.carrierDeletion base identified)
    {load : object.Vertex}
    (unpeeled : load ∈ unpeeledLoads support threshold receiver peeled)
    (declared : load ∈ family.declaredLoads identified)
    (eligibleLoad : eligible load)
    {boundary : Boundary} {left right : BoundaryPiece boundary}
    (sameBoundaryProfile :
      left.boundaryDegreeProfile = right.boundaryDegreeProfile)
    (targetDefect : Response.TargetDefect Target left right) :
    False :=
  noExitFour ⟨of_carrierDeletion family generated unpeeled declared
    sameBoundaryProfile targetDefect, eligibleLoad⟩

attribute [local instance] vertexDecEq

theorem routed
    (witness : Witness Target support threshold receiver peeled) :
    witness.load ∈ object.routedLoads support threshold receiver :=
  ((mem_unpeeledLoads (object := object) support threshold receiver).mp
    witness.unpeeled).1

theorem fresh
    (witness : Witness Target support threshold receiver peeled) :
    witness.load ∉ peeled :=
  ((mem_unpeeledLoads (object := object) support threshold receiver).mp
    witness.unpeeled).2

/-- The peeling set after charging this exit-`(4)` witness. -/
noncomputable def nextPeeled
    (witness : Witness Target support threshold receiver peeled) :
    Finset object.Vertex :=
  Finset.cons witness.load peeled witness.fresh

theorem nextPeeled_subset_routedLoads
    (witness : Witness Target support threshold receiver peeled)
    (inside : peeled ⊆ object.routedLoads support threshold receiver) :
    witness.nextPeeled ⊆ object.routedLoads support threshold receiver := by
  intro vertex member
  simp [nextPeeled] at member
  rcases member with rfl | member
  · exact witness.routed
  · exact inside member

theorem residualLoad_nextPeeled
    (witness : Witness Target support threshold receiver peeled) :
    residualLoad support threshold receiver witness.nextPeeled + 1 =
      residualLoad support threshold receiver peeled := by
  classical
  simpa [nextPeeled] using
    residualLoad_insert support threshold receiver witness.unpeeled

end Witness

/-! ## `def:typeA-exit4-peeling`: the peeling set is witnessed

*"`P₄(w) ⊆ ℒ(w)` … each listed load equipped with one exit-`(4)` witness."*
Every load of the peeling set was charged by an exit-`(4)` witness taken at an
earlier peeling state inside `P₄(w)`; the witness's own `fresh` clause records
that the load was unpeeled at that state.  The empty peeling set is witnessed,
and charging one more witness (`lem:typeA-exit4-discharge`) keeps the set
witnessed — which is what carries the property along the finite descent. -/
def PeeledByWitnesses (Target : FiniteObject.{u} → Prop)
    {object : FiniteObject.{u}} (support : Finset object.Vertex)
    (threshold : Nat) (receiver : object.Vertex)
    (peeled : Finset object.Vertex) : Prop :=
  ∀ load ∈ peeled, ∃ prior : Finset object.Vertex, prior ⊆ peeled ∧
    ∃ witness : Witness Target support threshold receiver prior,
      witness.load = load

theorem peeledByWitnesses_empty (Target : FiniteObject.{u} → Prop)
    {object : FiniteObject.{u}} (support : Finset object.Vertex)
    (threshold : Nat) (receiver : object.Vertex) :
    PeeledByWitnesses Target support threshold receiver ∅ :=
  fun _load member => absurd member (Finset.notMem_empty _)

theorem peeledByWitnesses_nextPeeled {Target : FiniteObject.{u} → Prop}
    {object : FiniteObject.{u}} {support : Finset object.Vertex}
    {threshold : Nat} {receiver : object.Vertex} {peeled : Finset object.Vertex}
    (witnessed : PeeledByWitnesses Target support threshold receiver peeled)
    (witness : Witness Target support threshold receiver peeled) :
    PeeledByWitnesses Target support threshold receiver witness.nextPeeled := by
  intro load member
  have member' : load = witness.load ∨ load ∈ peeled := by
    simpa [Witness.nextPeeled] using member
  rcases member' with rfl | member'
  · exact ⟨peeled, Finset.subset_cons _, witness, rfl⟩
  · obtain ⟨prior, priorSubset, witness', equal⟩ := witnessed load member'
    exact ⟨prior, priorSubset.trans (Finset.subset_cons _), witness', equal⟩

end Hypostructure.Graph.ExitFour
