import Hypostructure.Graph.ExitFourPeeling
import Hypostructure.Graph.Route8Carrier

/-!
# The canonical exit-`(4)` quotient family at a receiver

`def:typeA-exit4-family` fixes, at a saturated receiver `w`, a family
`𝒬₄(w)` of *boundary-degree-preserving response quotients* generated by five
canonical constructions -- the visible receiver-entry identifications, the
silent/excess basin quotient, the trace-local non-carrier quotient, the
continuation/cubic-switch quotient, and the two-carrier carrier-deletion
quotient -- and says:

> Exit (4) occurs precisely when one of these listed canonical quotients is
> target-defective.

The declared routed-load support is part of the canonical construction; the
definition lists it clause by clause, and in every clause it is *the routed
loads whose declared coordinate the quotient identifies or forgets*.  That is
the reading taken here, so the clause-by-clause list is derived from the
quotient rather than asserted alongside it.

`def:typeA-exit4-peeling` then defines an *exit-(4) witness for a routed load*
`u`: a quotient `q ∈ 𝒬₄(w)`, two realizations in the same boundary-degree
fibre, a compatible outside context distinguishing their target predicates, and
the requirement that the declared support of `q` contains the canonical
coordinate of `u`.  All four are `Family.Witness` below: the reading is
`Route8.Entry`, whose `state` presents every retained coordinate set on *one*
labelled boundary, so the two realizations are automatically in the same
boundary-degree fibre; the distinguishing context is `Response.TargetDefect`.

With the witness in hand `lem:typeA-exit4-discharge` is `Family.isPeeling_insert`
-- adjoining one witnessed unpeeled load is again a peeling set and drops
`L₄(w)` by exactly one -- and the descent
`lem:typeA-exit4-residual-routing` opens terminates at a witnessed peeling set
leaving the receiver unsaturated.

Nothing here knows a graph family, a manuscript node, a threshold, or a proof:
the family is quantified over its target predicate, its reading, its carrier
universe, and the canonical generation predicate its clauses supply.
-/

namespace Hypostructure.Graph.ExitFour

open Hypostructure

universe u

/-- **The five canonical generating constructions of `def:typeA-exit4-family`.**

A member of `𝒬₄(w)` records which construction generated it; the mathematical
content the exit consumes -- target-defectiveness and the declared routed-load
support -- is the same for all five, exactly as `lem:typeA-exit4-discharge`
uses them ("the quotient family `𝒬₄(w)` is canonical: its members are exactly
the visible-coordinate, silent-basin, trace-basin, continuation/switch, and
two-carrier deletion quotients"). -/
inductive Clause where
  /-- (Q1): the visible receiver-entry coordinate identifications. -/
  | visibleEntry
  /-- (Q2): the silent/excess boundary-response quotient of the basin `B(w)`. -/
  | silentBasin
  /-- (Q3): the trace-local non-carrier quotient of a trace basin. -/
  | traceBasin
  /-- (Q4): the finite continuation or cubic-switch quotient. -/
  | continuationSwitch
  /-- (Q5): the carrier-deletion quotient of a two-carrier route-8 entry. -/
  | carrierDeletion
  deriving DecidableEq, Repr

/-- **`𝒬₄(w)`**, at a receiver of a support.

`entry` is the receiver's declared reading: a finite family of declared
coordinates, each with the carrier support its declared support uses, presented
on one labelled boundary.  `coordinate` is the canonical coordinate a routed
load is given by `def:declared-coordinate-signature`, and `Generated` is the
family's own generation predicate: `Generated clause base identified` says the
listed construction `clause` generates, from the reading `base`, the quotient
that identifies or forgets exactly `identified`.

No construction is generated here.  A node that owns one of the five clauses
supplies it through `Generated`; every statement below is quantified over the
family, so no row invents a member and none is dropped. -/
structure Family (Target : FiniteObject.{u} → Prop) {object : FiniteObject.{u}}
    (support : Finset object.Vertex) (threshold : Nat)
    (receiver : object.Vertex) (Carrier : Type u) where
  /-- The receiver's declared reading, on one labelled boundary. -/
  entry : Route8.Entry Target Carrier
  /-- The canonical declared coordinate of a routed load. -/
  coordinate : object.Vertex → entry.Coordinate
  /-- Every routed load's canonical coordinate is declared by the reading. -/
  coordinate_declared : ∀ load ∈ object.routedLoads support threshold receiver,
    coordinate load ∈ entry.coordinates
  /-- The generation predicate of the five canonical constructions. -/
  Generated : Clause → Finset entry.Coordinate → Finset entry.Coordinate → Prop
  /-- A generated quotient is taken on a declared reading. -/
  generated_base : ∀ {clause base identified}, Generated clause base identified →
    base ⊆ entry.coordinates
  /-- A generated quotient identifies or forgets declared coordinates of the
  reading it is taken on. -/
  generated_identified : ∀ {clause base identified},
    Generated clause base identified → identified ⊆ base

namespace Family

variable {Target : FiniteObject.{u} → Prop} {object : FiniteObject.{u}}
variable {support : Finset object.Vertex} {threshold scale : Nat}
variable {receiver : object.Vertex} {Carrier : Type u}
variable (family : Family Target support threshold receiver Carrier)

attribute [local instance] vertexDecEq

/-- **One member of `𝒬₄(w)` is target-defective**: the two realizations of the
quotient -- the reading before and after the identification -- are separated by
one compatible outside context.  Both are presented on the reading's own
labelled boundary, so the member retains the boundary degree profile, which is
what `def:typeA-exit4-family` requires of every member. -/
def Defective (clause : Clause)
    (base identified : Finset family.entry.Coordinate) : Prop :=
  family.Generated clause base identified ∧
    Response.TargetDefect Target
      (family.entry.state (base \ identified)) (family.entry.state base)

/-- **The declared routed-load support of a member**: the routed loads whose
canonical declared coordinate the quotient identifies or forgets.  This is
`def:typeA-exit4-family`'s clause-by-clause list, read uniformly -- (Q1)'s
identified visible coordinates, (Q2)'s basin loads, (Q3)'s trace load, (Q4)'s
connector family, (Q5)'s indexed load. -/
noncomputable def declaredLoads
    (identified : Finset family.entry.Coordinate) : Finset object.Vertex :=
  letI : DecidablePred fun load : object.Vertex =>
      family.coordinate load ∈ identified :=
    fun _ => Classical.propDecidable _
  (object.routedLoads support threshold receiver).filter fun load =>
    family.coordinate load ∈ identified

theorem mem_declaredLoads {identified : Finset family.entry.Coordinate}
    {load : object.Vertex} :
    load ∈ family.declaredLoads identified ↔
      load ∈ object.routedLoads support threshold receiver ∧
        family.coordinate load ∈ identified := by
  letI : DecidablePred fun load : object.Vertex =>
      family.coordinate load ∈ identified :=
    fun _ => Classical.propDecidable _
  simp [declaredLoads]

theorem declaredLoads_subset (identified : Finset family.entry.Coordinate) :
    family.declaredLoads identified ⊆
      object.routedLoads support threshold receiver := by
  intro load member
  exact (family.mem_declaredLoads.mp member).1

/-- **Exit `(4)`** of `def:typeA-saturated-exits`: *"a quotient in the canonical
exit-(4) family `𝒬₄(w)` is target-defective"*. -/
def Occurs : Prop :=
  ∃ clause : Clause, ∃ base identified : Finset family.entry.Coordinate,
    family.Defective clause base identified

/-- **An exit-`(4)` witness for a routed load** (`def:typeA-exit4-peeling`): a
member of `𝒬₄(w)`, its two same-fibre realizations, the compatible outside
context distinguishing their target predicates, and the requirement that the
declared support of the member contains the canonical coordinate of the load. -/
def Witness (load : object.Vertex) : Prop :=
  ∃ clause : Clause, ∃ base identified : Finset family.entry.Coordinate,
    family.Defective clause base identified ∧
      load ∈ family.declaredLoads identified

theorem occurs_of_witness {load : object.Vertex}
    (witness : family.Witness load) : family.Occurs := by
  obtain ⟨clause, base, identified, defective, _⟩ := witness
  exact ⟨clause, base, identified, defective⟩

theorem mem_routedLoads_of_witness {load : object.Vertex}
    (witness : family.Witness load) :
    load ∈ object.routedLoads support threshold receiver := by
  obtain ⟨_, _, identified, _, declared⟩ := witness
  exact family.declaredLoads_subset identified declared

/-- **A peeling set** of `def:typeA-exit4-peeling`: a set of routed loads, each
equipped with one exit-`(4)` witness, and with no routed load listed twice --
the last clause being `Finset` membership itself. -/
structure IsPeeling (peeled : Finset object.Vertex) : Prop where
  /-- `P₄(w) ⊆ ℒ(w)`. -/
  inside : peeled ⊆ object.routedLoads support threshold receiver
  /-- Every listed load carries one exit-`(4)` witness. -/
  witnessed : ∀ load ∈ peeled, family.Witness load

theorem isPeeling_empty : family.IsPeeling ∅ where
  inside := Finset.empty_subset _
  witnessed := by intro load member; exact absurd member (Finset.notMem_empty load)

/-- **`lem:typeA-exit4-discharge`.**

*"If exit (4) occurs through a quotient `q ∈ 𝒬₄(w)` whose declared support
contains the canonical coordinate of an unpeeled routed load
`u ∈ ℒ(w) ∖ P₄(w)`, then `P₄(w) ∪ {u}` is a valid peeling set and the remaining
receiver deficit is reduced by exactly `1/4`."*

The no-duplicate condition is preserved because the load was unpeeled, and the
residual load drops by exactly one, which by `lem:typeA-exit4-peeling-charge` is
exactly one quarter of remaining deficit. -/
theorem isPeeling_insert {peeled : Finset object.Vertex}
    (peeling : family.IsPeeling peeled) {load : object.Vertex}
    (witness : family.Witness load) (fresh : load ∉ peeled) :
    family.IsPeeling (insert load peeled) ∧
      residualLoad support threshold receiver (insert load peeled) + 1 =
        residualLoad support threshold receiver peeled := by
  have routed : load ∈ object.routedLoads support threshold receiver :=
    family.mem_routedLoads_of_witness witness
  refine ⟨⟨insert_subset_routedLoads support threshold receiver peeling.inside
      routed, ?_⟩, ?_⟩
  · intro other member
    rcases Finset.mem_insert.mp member with same | earlier
    · exact same ▸ witness
    · exact peeling.witnessed other earlier
  · exact residualLoad_insert support threshold receiver
      ((mem_unpeeledLoads support threshold receiver).mpr ⟨routed, fresh⟩)

/-- **`lem:typeA-exit4-residual-routing`, with the descent it opens, carrying
the witnesses.**

*"If `L₄(w) ≥ 4q(w)`, then the unpeeled routed loads at `w` realize one of exits
(1)--(8).  If the realized exit is (4), the peeling set can be enlarged by one
additional unpeeled routed load."*

`step` is that reading at the exit-`(4)` case: while the peeled residual is
still saturated, some unpeeled routed load carries an exit-`(4)` witness in
`𝒬₄(w)`.  Each enlargement drops `L₄(w)` by exactly one, so the descent
terminates -- at a peeling set, every load of which carries its own witness,
whose residual leaves the receiver unsaturated. -/
theorem exists_unsaturated_isPeeling
    (step : ∀ peeled : Finset object.Vertex, family.IsPeeling peeled →
      SaturatedAfter support threshold scale receiver peeled →
      ∃ load ∈ unpeeledLoads support threshold receiver peeled,
        family.Witness load) :
    ∃ peeled : Finset object.Vertex, family.IsPeeling peeled ∧
      ¬ SaturatedAfter support threshold scale receiver peeled := by
  obtain ⟨peeled, _inside, peeling, unsaturated⟩ :=
    exists_unsaturated_peeling support threshold scale receiver
      (Retained := family.IsPeeling) family.isPeeling_empty
      (fun peeled _inside peeling saturated => by
        obtain ⟨load, unpeeled, witness⟩ := step peeled peeling saturated
        obtain ⟨routed, fresh⟩ :=
          (mem_unpeeledLoads support threshold receiver).mp unpeeled
        exact ⟨load, routed, fresh,
          (family.isPeeling_insert peeling witness fresh).1⟩)
  exact ⟨peeled, peeling, unsaturated⟩

end Family

/-! ## Clause (Q5), from a route-8 entry

The carrier-deletion clause is the one a route-8 reading generates on its own:
`lem:typeA-essential-deletion-witness` forces a deletion witness at every
essential carrier, `lem:typeA-deletion-witness-declared` says the forgotten
coordinate is declared and uses the deleted carrier, and
`lem:typeA-carrier-deletion-exit` reads that separation as the target defect.
The bridge below says only that a family whose `Generated` contains that
construction realizes exit `(4)`; it generates nothing itself. -/

/-- The coordinates a carrier deletion forgets: those the core reading retains
and the deletion does not. -/
noncomputable def deletionIdentified {Target : FiniteObject.{u} → Prop}
    {Carrier : Type u} [DecidableEq Carrier]
    (entry : Route8.Entry Target Carrier) (carrier : Carrier) :
    Finset entry.Coordinate :=
  entry.retained entry.essentialCore \
    entry.retained (entry.essentialCore.erase carrier)

/-- **Clause (Q5) is an exit-`(4)` occurrence.**

At an essential carrier of the reading, the deletion quotient is target-defective
(`Route8.Entry.deletion_targetDefect`), so as soon as the family's own generation
predicate lists that construction, exit `(4)` occurs. -/
theorem occurs_of_carrierDeletion {Target : FiniteObject.{u} → Prop}
    {object : FiniteObject.{u}} {support : Finset object.Vertex}
    {threshold : Nat} {receiver : object.Vertex} {Carrier : Type u}
    [DecidableEq Carrier]
    (family : Family Target support threshold receiver Carrier)
    {carrier : Carrier} (member : carrier ∈ family.entry.essentialCore)
    (generated : family.Generated Clause.carrierDeletion
      (family.entry.retained family.entry.essentialCore)
      (deletionIdentified family.entry carrier)) :
    family.Occurs := by
  refine ⟨Clause.carrierDeletion, family.entry.retained family.entry.essentialCore,
    deletionIdentified family.entry carrier, generated, ?_⟩
  have deleted :
      family.entry.retained family.entry.essentialCore \
          deletionIdentified family.entry carrier =
        family.entry.retained (family.entry.essentialCore.erase carrier) :=
    Finset.sdiff_sdiff_eq_self
      (family.entry.retained_mono (Finset.erase_subset _ _))
  rw [deleted]
  exact family.entry.deletion_targetDefect member

end Hypostructure.Graph.ExitFour
