import Hypostructure.Graph.Progress
import Hypostructure.Core.Residual.Focus

/-!
# Lexicographic progress: the legacy focused queries

**Legacy.**  `Graph/Progress.lean` holds the registered progress order the
entry spine's selection is minimal for.  This file holds the focused-stage
queries that used to read it, which reach `Core.Residual.Focus` and through it
the legacy `Core.Residual.Ledger`.

Separated so that the spine can name `lexicographicProgress` without importing
the legacy stage stack.  Nothing in the ported spine reaches this file.
-/

namespace Hypostructure.Graph

universe u v w

/-- Read the current graph from a focused minimal-counterexample context.  The
context remains predecessor-owned; this query only projects the graph needed
by downstream graph CTs. -/
def focusedMinimalContextObjectQuery
    {Previous : Type w}
    (focus : Core.Residual.Focus.Profile Previous)
    {Baseline : FiniteObject.{u} -> Prop}
    {BranchState : FiniteObject.{u} -> Type v}
    {Target : FiniteObject.{u} -> Prop}
    (context : Core.Residual.Focus.ActiveQuery focus
      (fun _previous _active =>
        Core.MinimalCounterexampleContext
          (problem Baseline BranchState) Target
          (lexicographicProgress Baseline BranchState))) :
    Core.Residual.Focus.ActiveQuery focus
      (fun _previous _active => FiniteObject.{u}) :=
  context.map fun _previous _active ctx => ctx.G


/-- Payload generated by Graph's focused lexicographic minimal-selection
executor. -/
abbrev FocusedLexicographicMinimalOutput
    {Previous : Type w}
    (focus : Core.Residual.Focus.Profile Previous)
    {Baseline : FiniteObject.{u} -> Prop}
    {BranchState : FiniteObject.{u} -> Type v}
    {Target : FiniteObject.{u} -> Prop}
    (_object : Core.Residual.Focus.ActiveQuery focus
      (fun _previous _active => FiniteObject.{u}))
    (_baseline : Core.Residual.Focus.ActiveQuery focus
      (fun previous active => Baseline (_object previous active)))
    (_avoids : Core.Residual.Focus.ActiveQuery focus
      (fun previous active => Not (Target (_object previous active))))
    (_stage : Previous) (_active : focus.Active _stage) :=
  Core.MinimalCounterexampleContext
    (problem Baseline BranchState) Target
    (lexicographicProgress Baseline BranchState)

/-- Exact focused residual after Graph selects a lexicographically minimal
counterexample. -/
abbrev FocusedLexicographicMinimalStage
    {Previous : Type w}
    (focus : Core.Residual.Focus.Profile Previous)
    {Baseline : FiniteObject.{u} -> Prop}
    {BranchState : FiniteObject.{u} -> Type v}
    {Target : FiniteObject.{u} -> Prop}
    (object : Core.Residual.Focus.ActiveQuery focus
      (fun _previous _active => FiniteObject.{u}))
    (baseline : Core.Residual.Focus.ActiveQuery focus
      (fun previous active => Baseline (object previous active)))
    (avoids : Core.Residual.Focus.ActiveQuery focus
      (fun previous active => Not (Target (object previous active)))) :=
  Core.Residual.Focus.Stage focus
    (FocusedLexicographicMinimalOutput (BranchState := BranchState)
      focus object baseline avoids)

/-- Focus inherited after Graph selects a lexicographically minimal
counterexample. -/
abbrev FocusedLexicographicMinimalProfile
    {Previous : Type w}
    (focus : Core.Residual.Focus.Profile Previous)
    {Baseline : FiniteObject.{u} -> Prop}
    {BranchState : FiniteObject.{u} -> Type v}
    {Target : FiniteObject.{u} -> Prop}
    (object : Core.Residual.Focus.ActiveQuery focus
      (fun _previous _active => FiniteObject.{u}))
    (baseline : Core.Residual.Focus.ActiveQuery focus
      (fun previous active => Baseline (object previous active)))
    (avoids : Core.Residual.Focus.ActiveQuery focus
      (fun previous active => Not (Target (object previous active)))) :=
  Core.Residual.Focus.successor focus
    (FocusedLexicographicMinimalOutput (BranchState := BranchState)
      focus object baseline avoids)

/-- Query the selected minimal graph context from the newest focused ledger
entry. -/
def focusedLexicographicMinimalContextQuery
    {Previous : Type w}
    (focus : Core.Residual.Focus.Profile Previous)
    {Baseline : FiniteObject.{u} -> Prop}
    {BranchState : FiniteObject.{u} -> Type v}
    {Target : FiniteObject.{u} -> Prop}
    (object : Core.Residual.Focus.ActiveQuery focus
      (fun _previous _active => FiniteObject.{u}))
    (baseline : Core.Residual.Focus.ActiveQuery focus
      (fun previous active => Baseline (object previous active)))
    (avoids : Core.Residual.Focus.ActiveQuery focus
      (fun previous active => Not (Target (object previous active)))) :
    Core.Residual.Focus.ActiveQuery
      (FocusedLexicographicMinimalProfile (BranchState := BranchState)
        focus object baseline avoids)
      (fun stage active =>
        FocusedLexicographicMinimalOutput (BranchState := BranchState)
          focus object baseline avoids stage.previous active) :=
  Core.Residual.Focus.ActiveQuery.latest

/-- Counted focused execution of Graph's lexicographic minimal-counterexample
selector. -/
noncomputable def executeFocusedLexicographicMinimalCounted
    {Previous : Type w}
    (focus : Core.Residual.Focus.Profile Previous)
    {Baseline : FiniteObject.{u} -> Prop}
    {BranchState : FiniteObject.{u} -> Type v}
    {Target : FiniteObject.{u} -> Prop}
    (object : Core.Residual.Focus.ActiveQuery focus
      (fun _previous _active => FiniteObject.{u}))
    (baseline : Core.Residual.Focus.ActiveQuery focus
      (fun previous active => Baseline (object previous active)))
    (avoids : Core.Residual.Focus.ActiveQuery focus
      (fun previous active => Not (Target (object previous active))))
    (stateOf : (current : FiniteObject.{u}) -> BranchState current)
    (previous : Previous) :
    Core.Counted
      (FocusedLexicographicMinimalStage (BranchState := BranchState)
        focus object baseline avoids) :=
  Core.Residual.Focus.runCounted focus
    (Output := FocusedLexicographicMinimalOutput
      (BranchState := BranchState) focus object baseline avoids) previous
    fun active _checks _exact =>
      selectLexicographicMinimal (object previous active)
        (baseline previous active) (avoids previous active)
        stateOf

/-- Public stage projection of Graph's lexicographic minimal-counterexample
selector. -/
noncomputable def executeFocusedLexicographicMinimal
    {Previous : Type w}
    (focus : Core.Residual.Focus.Profile Previous)
    {Baseline : FiniteObject.{u} -> Prop}
    {BranchState : FiniteObject.{u} -> Type v}
    {Target : FiniteObject.{u} -> Prop}
    (object : Core.Residual.Focus.ActiveQuery focus
      (fun _previous _active => FiniteObject.{u}))
    (baseline : Core.Residual.Focus.ActiveQuery focus
      (fun previous active => Baseline (object previous active)))
    (avoids : Core.Residual.Focus.ActiveQuery focus
      (fun previous active => Not (Target (object previous active))))
    (stateOf : (current : FiniteObject.{u}) -> BranchState current)
    (previous : Previous) :
    FocusedLexicographicMinimalStage (BranchState := BranchState)
      focus object baseline avoids :=
  (executeFocusedLexicographicMinimalCounted focus object baseline avoids
    stateOf previous).value

@[simp] theorem executeFocusedLexicographicMinimalCounted_checks
    {Previous : Type w}
    (focus : Core.Residual.Focus.Profile Previous)
    {Baseline : FiniteObject.{u} -> Prop}
    {BranchState : FiniteObject.{u} -> Type v}
    {Target : FiniteObject.{u} -> Prop}
    (object : Core.Residual.Focus.ActiveQuery focus
      (fun _previous _active => FiniteObject.{u}))
    (baseline : Core.Residual.Focus.ActiveQuery focus
      (fun previous active => Baseline (object previous active)))
    (avoids : Core.Residual.Focus.ActiveQuery focus
      (fun previous active => Not (Target (object previous active))))
    (stateOf : (current : FiniteObject.{u}) -> BranchState current)
    (previous : Previous) :
    (executeFocusedLexicographicMinimalCounted focus object baseline avoids
      stateOf previous).checks = focus.selectionBudget.checks previous := by
  rw [executeFocusedLexicographicMinimalCounted,
    Core.Residual.Focus.runCounted_checks]

/-- Predicate-form work theorem for Graph's focused minimal selector. -/
theorem executeFocusedLexicographicMinimalCounted_work_within
    {Previous : Type w}
    (focus : Core.Residual.Focus.Profile Previous)
    {Baseline : FiniteObject.{u} -> Prop}
    {BranchState : FiniteObject.{u} -> Type v}
    {Target : FiniteObject.{u} -> Prop}
    (object : Core.Residual.Focus.ActiveQuery focus
      (fun _previous _active => FiniteObject.{u}))
    (baseline : Core.Residual.Focus.ActiveQuery focus
      (fun previous active => Baseline (object previous active)))
    (avoids : Core.Residual.Focus.ActiveQuery focus
      (fun previous active => Not (Target (object previous active))))
    (stateOf : (current : FiniteObject.{u}) -> BranchState current)
    (previous : Previous) :
    focus.selectionBudget.Within previous
      (executeFocusedLexicographicMinimalCounted focus object baseline avoids
        stateOf previous).checks :=
  Core.Residual.Focus.runCounted_work_within focus previous _

/-- A raw smaller graph carrying the same baseline and target avoidance is
closed by the selected Core minimality kernel.  The caller does not construct
or copy an `AvoidingContext`. -/
theorem contradiction_of_smallerAvoidingGraph
    {Baseline : FiniteObject.{u} -> Prop}
    {BranchState : FiniteObject.{u} -> Type v}
    {Target : FiniteObject.{u} -> Prop}
    (ctx : Core.MinimalCounterexampleContext
      (problem Baseline BranchState) Target
      (lexicographicProgress Baseline BranchState))
    (candidate : FiniteObject.{u})
    (baseline : Baseline candidate)
    (state : BranchState candidate)
    (avoids : Not (Target candidate))
    (smaller : (lexicographicProgress Baseline BranchState).Smaller
      candidate ctx.G) : False :=
  ctx.contradiction_of_smaller
    (Core.AvoidingContext.ofBranch
      ({ G := candidate, baseline := baseline, state := state } :
        Core.BranchContext (problem Baseline BranchState))
      avoids)
    smaller

end Hypostructure.Graph
