import Hypostructure.Graph.RootedReturn
import Hypostructure.Core.Residual.Focus

/-!
# Rooted-return avoidance: the legacy focused queries

**Legacy.**  `Graph/RootedReturn.lean` holds the return-set mathematics --
`lem:return-equivalence` and the disjointness characterisation the entry
spine's nodes `[5]`--`[7]` prove.  This file holds the focused-stage queries
that used to carry it, which reach `Core.Residual.Focus` and through it the
legacy `Core.Residual.Ledger`.

They are separated so that the spine's row can consume
`not_hasCycleWithLength_iff_returnLengthSets_disjoint` without importing the
legacy stage stack.  Nothing in the ported spine reaches this file.
-/

namespace Hypostructure.Graph

universe u v w

namespace RootedReturnTargetAlgebra

variable {CycleLengthOK : Nat → Prop}

/-- Read public target avoidance from a focused rooted-return avoidance
certificate.  The certificate remains ledger-owned; this query only exposes
the target-negation shape required by CT1's avoiding continuation. -/
def focusedAvoidanceNotTargetQuery
    {Previous : Type v}
    (profile : RootedReturnTargetAlgebra CycleLengthOK)
    (focus : Core.Residual.Focus.Profile Previous)
    (object : Core.Residual.Focus.ActiveQuery focus
      (fun _previous _active => FiniteObject.{u}))
    (certificate : Core.Residual.Focus.ActiveQuery focus
      (fun previous active =>
        profile.AvoidanceCertificate (object previous active))) :
    Core.Residual.Focus.ActiveQuery focus
      (fun previous active =>
        Not (HasCycleWithLength CycleLengthOK
          (object previous active))) :=
  certificate.map fun _previous _active cert => cert.notTarget

/-- The focused payload generated by Graph's rooted-return avoidance
projection from a minimal target-avoiding graph context. -/
abbrev FocusedAvoidanceCertificateOutput
    {Previous : Type w}
    (focus : Core.Residual.Focus.Profile Previous)
    {Baseline : FiniteObject.{u} -> Prop}
    {BranchState : FiniteObject.{u} -> Type v}
    (profile : RootedReturnTargetAlgebra CycleLengthOK)
    (context : Core.Residual.Focus.ActiveQuery focus
      (fun _previous _active =>
        Core.MinimalCounterexampleContext
          (problem Baseline BranchState)
          (HasCycleWithLength CycleLengthOK)
          (lexicographicProgress Baseline BranchState)))
    (stage : Previous) (active : focus.Active stage) :=
  profile.AvoidanceCertificate (context stage active).G

/-- Exact focused residual after Graph records rooted-return target avoidance. -/
abbrev FocusedAvoidanceCertificateStage
    {Previous : Type w}
    (focus : Core.Residual.Focus.Profile Previous)
    {Baseline : FiniteObject.{u} -> Prop}
    {BranchState : FiniteObject.{u} -> Type v}
    (profile : RootedReturnTargetAlgebra CycleLengthOK)
    (context : Core.Residual.Focus.ActiveQuery focus
      (fun _previous _active =>
        Core.MinimalCounterexampleContext
          (problem Baseline BranchState)
          (HasCycleWithLength CycleLengthOK)
          (lexicographicProgress Baseline BranchState))) :=
  Core.Residual.Focus.Stage focus
    (FocusedAvoidanceCertificateOutput focus profile context)

/-- Focus inherited after Graph records rooted-return target avoidance. -/
abbrev FocusedAvoidanceCertificateProfile
    {Previous : Type w}
    (focus : Core.Residual.Focus.Profile Previous)
    {Baseline : FiniteObject.{u} -> Prop}
    {BranchState : FiniteObject.{u} -> Type v}
    (profile : RootedReturnTargetAlgebra CycleLengthOK)
    (context : Core.Residual.Focus.ActiveQuery focus
      (fun _previous _active =>
        Core.MinimalCounterexampleContext
          (problem Baseline BranchState)
          (HasCycleWithLength CycleLengthOK)
          (lexicographicProgress Baseline BranchState))) :=
  Core.Residual.Focus.successor focus
    (FocusedAvoidanceCertificateOutput focus profile context)

/-- Query Graph's rooted-return avoidance certificate from the newest
focused ledger entry. -/
def focusedAvoidanceCertificateQuery
    {Previous : Type w}
    (focus : Core.Residual.Focus.Profile Previous)
    {Baseline : FiniteObject.{u} -> Prop}
    {BranchState : FiniteObject.{u} -> Type v}
    (profile : RootedReturnTargetAlgebra CycleLengthOK)
    (context : Core.Residual.Focus.ActiveQuery focus
      (fun _previous _active =>
        Core.MinimalCounterexampleContext
          (problem Baseline BranchState)
          (HasCycleWithLength CycleLengthOK)
          (lexicographicProgress Baseline BranchState))) :
    Core.Residual.Focus.ActiveQuery
      (FocusedAvoidanceCertificateProfile focus profile context)
      (fun stage active =>
        FocusedAvoidanceCertificateOutput focus profile context
          stage.previous active) :=
  Core.Residual.Focus.ActiveQuery.latest

/-- Counted focused execution of Graph's rooted-return avoidance projection. -/
noncomputable def executeFocusedAvoidanceCertificateCounted
    {Previous : Type w}
    (focus : Core.Residual.Focus.Profile Previous)
    {Baseline : FiniteObject.{u} -> Prop}
    {BranchState : FiniteObject.{u} -> Type v}
    (profile : RootedReturnTargetAlgebra CycleLengthOK)
    (context : Core.Residual.Focus.ActiveQuery focus
      (fun _previous _active =>
        Core.MinimalCounterexampleContext
          (problem Baseline BranchState)
          (HasCycleWithLength CycleLengthOK)
          (lexicographicProgress Baseline BranchState)))
    (previous : Previous) :
    Core.Counted
      (FocusedAvoidanceCertificateStage focus profile context) :=
  Core.Residual.Focus.runCounted focus previous
    fun active _checks _exact =>
      let ctx := context previous active
      profile.avoidanceCertificate ctx.G ctx.avoids

/-- Public stage projection of Graph's rooted-return avoidance projection. -/
noncomputable def executeFocusedAvoidanceCertificate
    {Previous : Type w}
    (focus : Core.Residual.Focus.Profile Previous)
    {Baseline : FiniteObject.{u} -> Prop}
    {BranchState : FiniteObject.{u} -> Type v}
    (profile : RootedReturnTargetAlgebra CycleLengthOK)
    (context : Core.Residual.Focus.ActiveQuery focus
      (fun _previous _active =>
        Core.MinimalCounterexampleContext
          (problem Baseline BranchState)
          (HasCycleWithLength CycleLengthOK)
          (lexicographicProgress Baseline BranchState)))
    (previous : Previous) :
    FocusedAvoidanceCertificateStage focus profile context :=
  (executeFocusedAvoidanceCertificateCounted focus profile context previous).value

@[simp] theorem executeFocusedAvoidanceCertificateCounted_checks
    {Previous : Type w}
    (focus : Core.Residual.Focus.Profile Previous)
    {Baseline : FiniteObject.{u} -> Prop}
    {BranchState : FiniteObject.{u} -> Type v}
    (profile : RootedReturnTargetAlgebra CycleLengthOK)
    (context : Core.Residual.Focus.ActiveQuery focus
      (fun _previous _active =>
        Core.MinimalCounterexampleContext
          (problem Baseline BranchState)
          (HasCycleWithLength CycleLengthOK)
          (lexicographicProgress Baseline BranchState)))
    (previous : Previous) :
    (executeFocusedAvoidanceCertificateCounted focus profile context
      previous).checks = focus.selectionBudget.checks previous := by
  rw [executeFocusedAvoidanceCertificateCounted,
    Core.Residual.Focus.runCounted_checks]

/-- Predicate-form work theorem for Graph's rooted-return avoidance
projection. -/
theorem executeFocusedAvoidanceCertificateCounted_work_within
    {Previous : Type w}
    (focus : Core.Residual.Focus.Profile Previous)
    {Baseline : FiniteObject.{u} -> Prop}
    {BranchState : FiniteObject.{u} -> Type v}
    (profile : RootedReturnTargetAlgebra CycleLengthOK)
    (context : Core.Residual.Focus.ActiveQuery focus
      (fun _previous _active =>
        Core.MinimalCounterexampleContext
          (problem Baseline BranchState)
          (HasCycleWithLength CycleLengthOK)
          (lexicographicProgress Baseline BranchState)))
    (previous : Previous) :
    focus.selectionBudget.Within previous
      (executeFocusedAvoidanceCertificateCounted focus profile context
        previous).checks :=
  Core.Residual.Focus.runCounted_work_within focus previous _

end RootedReturnTargetAlgebra

end Hypostructure.Graph
