import Hypostructure.Graph.VisibleReceiverEntry
import Hypostructure.Graph.ExitFourFamily

/-!
# Clause (Q1) of `def:typeA-exit4-family`: the visible-entry identifications

> The family `𝒬₄(w)` consists of boundary-degree-preserving response quotients
> generated by the following canonical constructions.
> (Q1) the visible receiver-entry coordinate identifications tested in
> `lem:typeA-visible-entry`.
> […] The declared routed-load support is part of the canonical construction:
> in (Q1) it is the set of visible routed loads whose response coordinates are
> identified.

`Graph.ExitFour.ReceiverFamily` is the family read as data: a declared
coordinate family, the canonical coordinate of a routed load, and a generation
predicate `Generated` saying which of the four pre-route clauses produces
which quotient.  Row 16 quantifies over the family, so it never invents a
member; the clauses have to be supplied by the nodes that own them, and (Q1) is
node `[93]`'s.

This file supplies exactly (Q1), and nothing else:

* `visibleCoordinates` is the set of declared coordinates the identification
  collapses -- those of the visible routed loads at one completion port,
  intersected with the reading the quotient is taken on;
* `Q1Generated` is the generation predicate carrying only that clause;
* `visibleEntryFamily` is the resulting `𝒬₄(w)` at an arbitrary declared
  reading, with the two structural laws proved rather than assumed;
* `visibleLoads_subset_declaredLoads` is the manuscript's declared-support
  clause for (Q1).

The reading stays a parameter.  It is the *route-8 entry's* reading, owned by
nodes `[109]` onwards, and (Q1) is a statement about whichever reading a
receiver carries -- so quantifying over it is the faithful formalization, not a
weakening.  Nothing here reads a numeral, a baseline or a scale.
-/

namespace Hypostructure.Graph.VisibleEntry

open Hypostructure

universe u

variable {object : FiniteObject.{u}}

section Clause

variable {Target : FiniteObject.{u} → Prop} {Coordinate : Type u}
variable [DecidableEq Coordinate]
variable (support : Finset object.Vertex) (threshold : Nat)
variable (receiver : object.Vertex)
variable (coordinates : Finset Coordinate)
variable (coordinate : object.Vertex → Coordinate)

/-- **The coordinates (Q1) identifies at one completion port.**

The visible receiver-entry test at `⃗e = (w,h)` names a set of routed loads --
`L_vis(w, ⃗e)` -- and the identification it induces on the reading collapses
their declared response coordinates.  Intersecting with `base` is what makes the
result a quotient *of that reading*, which is the boundary-degree preservation
`def:typeA-exit4-family` demands of every member. -/
noncomputable def visibleCoordinates (outside : object.Vertex)
    (base : Finset Coordinate) : Finset Coordinate := by
  classical
  exact base.filter fun declared =>
    ∃ load ∈ visibleLoadsAt object support threshold receiver outside,
      coordinate load = declared

theorem mem_visibleCoordinates {outside : object.Vertex}
    {base : Finset Coordinate} {declared : Coordinate} :
    declared ∈ visibleCoordinates support threshold receiver coordinate
        outside base ↔
      declared ∈ base ∧
        ∃ load ∈ visibleLoadsAt object support threshold receiver outside,
          coordinate load = declared := by
  classical
  simp [visibleCoordinates]

theorem visibleCoordinates_subset (outside : object.Vertex)
    (base : Finset Coordinate) :
    visibleCoordinates support threshold receiver coordinate outside base ⊆
      base :=
  Finset.filter_subset _ _

/-- **Clause (Q1) as a generation predicate.**

`Q1Generated clause base identified` holds exactly when `clause` is the
visible-entry clause, `base` is a reading of the entry, and `identified` is the
visible-entry identification at some completion port of the receiver.  No other
clause is generated here: (Q2)--(Q4) are other nodes' constructions, and a
family generating only (Q1) is still a family, because
the structural generator metadata records the clause and its declared support. -/
def Q1Generated (outside : object.Vertex) :
    Graph.ExitFour.ReceiverClause → Finset Coordinate →
      Finset Coordinate → Prop :=
  fun clause base identified =>
    clause = Graph.ExitFour.ReceiverClause.visibleEntry ∧
      base ⊆ coordinates ∧
        identified =
          visibleCoordinates support threshold receiver coordinate outside base

/-- **`𝒬₄(w)` generated by (Q1) at one completion port.**

The two structural laws of `Graph.ExitFour.ReceiverFamily` -- that a generated quotient
is taken on a declared reading and identifies declared coordinates of it -- are
proved from the definition: the first is `Q1Generated`'s own second component,
the second is `visibleCoordinates` being a filter of `base`. -/
noncomputable def visibleEntryFamily (outside : object.Vertex)
    (declared : ∀ load ∈ object.routedLoads support threshold receiver,
      coordinate load ∈ coordinates) :
    Graph.ExitFour.ReceiverFamily Target support threshold receiver where
  Coordinate := Coordinate
  coordinateDecEq := ‹DecidableEq Coordinate›
  coordinates := coordinates
  coordinate := coordinate
  coordinate_declared := declared
  Generated := Q1Generated support threshold receiver coordinates coordinate
    outside
  generated_base := by
    rintro _ _ _ ⟨_, readings, _⟩
    exact readings
  generated_identified := by
    rintro _ base _ ⟨_, _, rfl⟩
    exact visibleCoordinates_subset support threshold receiver coordinate outside
      base

/-- **The (Q1) member is generated**, at every reading of the entry.  This is
the statement node `[93]` owes `def:typeA-exit4-family`: the family it hands
row 16 is nonempty at the visible-entry clause. -/
theorem generated_visibleEntry (outside : object.Vertex)
    (declared : ∀ load ∈ object.routedLoads support threshold receiver,
      coordinate load ∈ coordinates)
    (base : Finset Coordinate) (readings : base ⊆ coordinates) :
    (visibleEntryFamily support threshold receiver coordinates coordinate outside
        declared).Generated
      Graph.ExitFour.ReceiverClause.visibleEntry base
      (visibleCoordinates support threshold receiver coordinate outside base) :=
  ⟨rfl, readings, rfl⟩

/-- **(Q1)'s declared routed-load support.**

*"In (Q1) it is the set of visible routed loads whose response coordinates are
identified."*  A visible routed load whose coordinate lies in the reading is a
declared load of the member, which is what lets exit `(4)` peel a visible load
in `def:typeA-exit4-peeling`. -/
theorem visibleLoads_subset_declaredLoads (outside : object.Vertex)
    (declared : ∀ load ∈ object.routedLoads support threshold receiver,
      coordinate load ∈ coordinates)
    (base : Finset Coordinate) :
    (visibleLoadsAt object support threshold receiver outside).filter
        (fun load => coordinate load ∈ base) ⊆
      (visibleEntryFamily support threshold receiver coordinates coordinate outside
          declared).declaredLoads
        (visibleCoordinates support threshold receiver coordinate outside base) := by
  classical
  intro load member
  obtain ⟨visible, inBase⟩ := Finset.mem_filter.mp member
  refine (visibleEntryFamily support threshold receiver coordinates coordinate
    outside declared).mem_declaredLoads.mpr
    ⟨visibleLoadsAt_subset object support threshold receiver outside visible,
      ?_⟩
  exact (mem_visibleCoordinates support threshold receiver coordinate).mpr
    ⟨inBase, load, visible, rfl⟩

/-- **Conversely, every declared load of the (Q1) member is a routed load whose
coordinate the identification collapses.**  Together with the inclusion above
this is `def:typeA-exit4-family`'s clause read in both directions: the member's
support is cut out of the routed loads by the visible-entry identification and
by nothing else. -/
theorem mem_declaredLoads_visibleCoordinates (outside : object.Vertex)
    (declared : ∀ load ∈ object.routedLoads support threshold receiver,
      coordinate load ∈ coordinates)
    (base : Finset Coordinate) {load : object.Vertex} :
    load ∈
        (visibleEntryFamily support threshold receiver coordinates coordinate outside
            declared).declaredLoads
          (visibleCoordinates support threshold receiver coordinate outside
            base) ↔
      load ∈ object.routedLoads support threshold receiver ∧
        coordinate load ∈ base ∧
        ∃ seen ∈ visibleLoadsAt object support threshold receiver outside,
          coordinate seen = coordinate load := by
  classical
  constructor
  · intro member
    obtain ⟨routed, identified⟩ :=
      (visibleEntryFamily support threshold receiver coordinates coordinate
        outside declared).mem_declaredLoads.mp member
    obtain ⟨inBase, seen⟩ :=
      (mem_visibleCoordinates support threshold receiver coordinate).mp
        identified
    exact ⟨routed, inBase, seen⟩
  · rintro ⟨routed, inBase, seen⟩
    exact (visibleEntryFamily support threshold receiver coordinates coordinate
      outside declared).mem_declaredLoads.mpr
      ⟨routed, (mem_visibleCoordinates support threshold receiver
        coordinate).mpr ⟨inBase, seen⟩⟩

/-! ## (Q1) on the full reading

`𝒬₄(w)` is generated *from the reading*, so the member node `[93]` exhibits is
the one taken on the full declared coordinate set.  There the hypothesis "every
visible load has a declared coordinate" is not an assumption: it is
`coordinate_declared` composed with `visibleLoadsAt ⊆ routedLoads`. -/

/-- **Every visible load at the port is a declared load of the (Q1) member.** -/
theorem visibleLoadsAt_subset_declaredLoads (outside : object.Vertex)
    (declared : ∀ load ∈ object.routedLoads support threshold receiver,
      coordinate load ∈ coordinates) :
    visibleLoadsAt object support threshold receiver outside ⊆
      (visibleEntryFamily support threshold receiver coordinates coordinate outside
          declared).declaredLoads
        (visibleCoordinates support threshold receiver coordinate outside
          coordinates) := by
  classical
  intro load visible
  refine (visibleEntryFamily support threshold receiver coordinates coordinate
    outside declared).mem_declaredLoads.mpr
    ⟨visibleLoadsAt_subset object support threshold receiver outside visible,
      ?_⟩
  refine (mem_visibleCoordinates support threshold receiver coordinate).mpr
    ⟨?_, load, visible, rfl⟩
  exact declared load
    (visibleLoadsAt_subset object support threshold receiver outside visible)

/-- **A port that carries a visible load gives a nontrivial (Q1) member.**

This is the branch content of clause (Q1): the identification collapses nothing
at a silent port, and collapses at least one declared coordinate at a port that
sees a routed load.  It is what makes `def:typeA-exit4-peeling` able to remove a
*visible* load when exit `(4)` is taken through this clause. -/
theorem visibleCoordinates_nonempty (outside : object.Vertex)
    (declared : ∀ load ∈ object.routedLoads support threshold receiver,
      coordinate load ∈ coordinates)
    (seen : (visibleLoadsAt object support threshold receiver outside).Nonempty) :
    (visibleCoordinates support threshold receiver coordinate outside
      coordinates).Nonempty := by
  classical
  obtain ⟨load, visible⟩ := seen
  refine ⟨coordinate load, ?_⟩
  refine (mem_visibleCoordinates support threshold receiver coordinate).mpr
    ⟨?_, load, visible, rfl⟩
  exact declared load
    (visibleLoadsAt_subset object support threshold receiver outside visible)

end Clause

end Hypostructure.Graph.VisibleEntry
