import Hypostructure.Graph.Strategy.SpineRows
import Hypostructure.Graph.ColdIncrementArithmetic

/-!
# The cold return corridor: rows `[145]`--`[157]`

Each declaration below is an ordinary atomic Strategy at the spine vocabulary.
It publishes a concrete `Spine.Key` fact and consumes predecessors only through
sealed `FactInputs.get`.

`coldCorridorStateRow` commits `def:cold-corridor-first-failure`'s cut-state
clauses: the cold corridor state is *complete* for the local replacement and
*bounded* by `Q_cold`.  It reads nothing from the ledger, because neither
clause depends on anything the earlier nodes proved: both are theorems about
the registered declared signature.

`sameInterfaceTableRow` commits `lem:cold-same-interface-table` together with
`lem:cold-short-self-return-filter`.  It reads exactly the two facts the
manuscript's proof spends -- node `[1]`'s target avoidance and node `[14]`'s
uncompressibility -- and nothing else.  A realizing row would hand the selected
object the target it avoids; a row that is neither handed off nor
distinguishing is a target-complete compression of its own proper support,
which node `[14]` has excluded.  So no row of the table is terminal.
-/

namespace Hypostructure.Graph.Strategy.Spine

open Hypostructure
open Hypostructure.Core.Residual
open Hypostructure.Core.Strategy

universe u v

variable {BranchState : Graph.FiniteObject.{u} → Type v}
variable {Presentation : Type} {presentation : Presentation}
variable {data : Data.{u}}

/-! ## Nodes `[145]`--`[157]`: the corridor cut-state `T(J)`

`def:cold-corridor-first-failure` fixes, for an initial segment `J` of a cold
return corridor, its two active boundary interfaces `T(J)` and the cold
corridor state of `J`: the finite two-boundary cut-state obtained from
`ρ^ex_{T(J)}(J)` by retaining exactly the boundary-degree profile, the two
active boundary half-edges, the cold-window offsets met at the two interfaces,
and the declared local coordinates whose support is contained in the bounded
active interface.  "It is not the full labelled prefix."

The row commits the two things that retention has to earn.

*Completeness.*  The manuscript's "after excluding (F2), equality of cold
corridor states is equality for every target-response coordinate used by the
local replacement".  The state retains no (D8) coordinate at all -- no product,
labelled copy, restriction, or quotient image -- and it does not need to: an
(D8) coordinate reads exactly the entries it was generated from, so once the
generating readings agree the derived reading agrees.  That is
`Presentation.reading_eq_of_state_eq`, by induction on the generation.

*Boundedness.*  "Since the boundary has size two and the retained window and
local-coordinate labels are finite, the set of possible cold corridor states is
bounded by a constant `Q_cold` depending only on the fixed declared signature."
`Q_cold` is `Fintype.card` of the retained cut-state of the *registered*
signature, so it mentions no graph, and `Q_cold + 1` segments cannot have
pairwise distinct states.  That pigeonhole is how
`lem:cold-corridor-first-failure` reaches the repeat subcase of (F5).

The row quantifies over every presentation of the object's corridor segments
rather than naming one.  A corridor is data, and no fact can carry data; what
the statement says is that the retention works at every corridor, which is what
the manuscript claims and what a later node needs. -/
@[reducible] noncomputable def coldCorridorStateRow :
    AtomicStrategy (Input BranchState Presentation presentation data) :=
  factOnly `Hypostructure.Graph.Strategy.Spine.coldCorridorState
    { Requires := []
      Produces := [K .coldCorridorState]
      requiresUnique := by simp
      producesUnique := by simp
      producesNonempty := by simp }
    (fun inputs =>
      .cons (key := K .coldCorridorState)
        ⟨fun presentation' =>
          ⟨fun _left _right same coordinate inside =>
              presentation'.reading_eq_of_state_eq same coordinate inside,
            presentation'.exists_state_eq_of_stateBound_lt,
            fun _boundary _carrier _left _right =>
              ⟨fun excluded same =>
                  presentation'.contextEquivalent_of_state_eq excluded same,
                fun same separated =>
                  presentation'.firstFailureResponse_of_not_contextEquivalent same
                    separated⟩⟩⟩
        .nil)

/-! ## Nodes `[145]`--`[157]`: the same-interface table

`def:cold-same-interface-table` is the finite table whose rows are equal-length
cold bounded germs and the short self-return exceptions of
`lem:cold-short-self-return-filter`, each row recording (T1) the two boundary
vertices and their boundary-degree profile, (T2) the two terminal cold-window
stubs and their offsets, (T3) the exact response profile generated by
`def:declared-coordinate-signature`, and (T4) the target truth value of every
compatible completion represented by that exact profile.

`lem:cold-same-interface-table` closes every row of it, and the manuscript's
proof spends exactly two things this branch already carries.

If a row is *realizing*, "the corresponding completion is a power-of-two cycle
in `G`, which contradicts the counterexample condition": the corridor
representative glued to its own outside context *is* the selected object, up to
the decomposition's reconstruction isomorphism, so the selection's own
avoidance excludes it.

If a row "first meets a declared Type B or route-8 interface", the handoff
alternative reads the corresponding support predicate from the incoming ledger.
The row does not allocate or transport a separate handoff object.

Otherwise the row is *distinguishing* or *neutral*.  Neutrality "means that the
two representatives have the same boundary-degree profile and the same target
response against every compatible context", and then
`def:admissible-rank-quotient` supplies the strictly smaller proper
representative of `def:proper-quotient-representative`.  Every clause of a
target-complete proper-support compression is then present, and node `[14]`'s
`cor:uncompressible` forbids it.  So a row is handed off or distinguishing, and
no equal-length cold bounded germ is a terminal cold residual.

The second output clause is the filter itself: a cold-window outside
self-return of outside length `ℓ` is smeared over the window offsets, testing
`[ℓ, ℓ+order−1]`, and a length that does not survive that test realizes an
accepted cycle.  The surviving lengths are the exceptional rows of the table,
which the first clause closes with the germs. -/
@[reducible] noncomputable def sameInterfaceTableRow :
    AtomicStrategy (Input BranchState Presentation presentation data) :=
  factOnly `Hypostructure.Graph.Strategy.Spine.coldSameInterfaceTable
    { Requires := [K .selection, K .uncompressible]
      Produces := [K .coldSameInterfaceTable]
      requiresUnique := by simp
      producesUnique := by simp
      producesNonempty := by simp }
    (fun inputs =>
      .cons (key := K .coldSameInterfaceTable)
        ⟨
          ⟨fun _Handoff row =>
              Graph.ColdCorridor.row_closed
                (Graph.cycleTargetInterface data.LengthOK).isomorphismInvariant
                (inputs.get (K .selection)).down.1
                (inputs.get (K .uncompressible)).down row,
            fun _Handoff self =>
              Graph.ColdCorridor.selfReturn_closed
                (Graph.cycleTargetInterface data.LengthOK).isomorphismInvariant
                (inputs.get (K .selection)).down.1
                (inputs.get (K .uncompressible)).down self,
            fun _length failed =>
              Graph.ColdCorridor.exists_accepted_of_not_survivesSmear failed,
            rfl,
            fun _Handoff row => row.increment_eq_zero⟩⟩
        .nil)


/-! ## Nodes `[155]`--`[157]`: `lem:cold-bounded-germ-trichotomy`

*"No length-changing cold bounded germ survives on the cold residual.  More
explicitly, every such germ falls into one of the following three cases."*

One row per arm, because the manuscript routes the three arms to three
different places: G1 to the counterexample condition, G2 to the sparse exit or
exit-(4) ledger, and G3 to `cor:uncompressible`.  Each row commits the arm its
own node owns and reads exactly the facts that arm's proof spends -- node `[1]`'s
target avoidance for G1, node `[14]`'s uncompressibility for G3, and nothing at
all for G2, which is `lem:context-universality` at the germ.

`Graph.ColdCorridor.BoundedGerm` is `def:cold-bounded-germ` itself, and the
equal-length rows of `def:cold-same-interface-table` are the same structure with
`δ = 0` added; the two halves of the definition therefore share one shape and
no germ can be a row of one family and not of the other. -/

/-- **Node `[155]`: the G1 arm, and the exhaustiveness of the trichotomy.**

*"Hit-realized.  Some compatible live completion and window offset close a
dyadic cycle.  This contradicts the counterexample condition."*  A germ's own
compatible completion is the selected object up to the decomposition's
reconstruction isomorphism, so a realizing germ hands it the target node `[1]`
denies.  Beside it the row commits the split's exhaustiveness, which is what
makes the routing of G2 and G3 a routing of everything that is left. -/
@[reducible] noncomputable def coldGermRealizedRow :
    AtomicStrategy (Input BranchState Presentation presentation data) :=
  factOnly `Hypostructure.Graph.Strategy.Spine.coldGermRealized
    (rowManifest (K .selection) (K .coldGermRealized) (by simp))
    (fun inputs =>
      .cons (key := K .coldGermRealized)
        ⟨
          ⟨fun germ realizing =>
              (inputs.get (K .selection)).down.1
                (germ.target_of_realizing
                  (Graph.cycleTargetInterface data.LengthOK).isomorphismInvariant
                  realizing),
            fun germ => germ.trichotomy⟩⟩
        .nil)

/-- **Node `[156]`: the G2 arm.**

*"Hit-distinguished.  Some compatible outside context distinguishes the two
representatives by dyadic truth value without already realizing the cycle in the
current graph.  The induced quotient is target-defective, so it is routed to the
sparse exit or exit-(4) ledger."*  Its proof is `lem:context-universality`: the
distinguishing context already denies the all-context clause of
`def:target-complete-quotient`, so the identification fails to be target-complete
in every immutable profile fibre.

The row reads nothing.  Target-defectiveness of a distinguished germ is a
theorem about the germ's own two representatives; the branch facts are spent by
the other two arms. -/
@[reducible] noncomputable def coldGermDistinguishedRow :
    AtomicStrategy (Input BranchState Presentation presentation data) :=
  factOnly `Hypostructure.Graph.Strategy.Spine.coldGermDistinguished
    (sourceFreeManifest (K .coldGermDistinguished))
    (fun inputs =>
      .cons (key := K .coldGermDistinguished)
        ⟨
          (fun germ _Profile profile distinguishing =>
            germ.not_targetComplete_of_distinguishing profile distinguishing)⟩
        .nil)

/-- **Node `[157]`: the G3 arm, with `lem:cold-increment-arithmetic`.**

*"Silent.  No compatible outside context and no relevant scale distinguishes the
two representatives.  Then replacing the longer representative by the shorter one
… strictly decreases the support.  This is a nontrivial target-complete
compression of a proper support"*, forbidden by `cor:uncompressible`, which is
node `[14]`'s fact and the only thing this row reads.

Unlike the equal-length rows of `def:cold-same-interface-table`, the descent is
the increment's own: the shorter representative has strictly fewer internal
vertices, so its completion has strictly fewer vertices than the object, and no
appeal to `def:admissible-rank-quotient` is made.

The remaining outputs are `lem:cold-increment-arithmetic`, which decides which
arm a length-changing germ falls into: the overlapping blocks of case (a), the
attainable power of two of case (b), the order criterion `ord_δ(2) > δ − 13`
that forces (b), the transient reduction of an even modulus to its odd part, and
case (d)'s equal-length switch back to the same-interface table.  Case (c) is the
trichotomy's own exhaustiveness, committed at node `[155]`. -/
@[reducible] noncomputable def coldGermSilentRow :
    AtomicStrategy (Input BranchState Presentation presentation data) :=
  factOnly `Hypostructure.Graph.Strategy.Spine.coldGermSilent
    (rowManifest (K .uncompressible) (K .coldGermSilent) (by simp))
    (fun inputs =>
      .cons (key := K .coldGermSilent)
        ⟨
          ⟨fun germ shorter neutral =>
              (inputs.get (K .uncompressible)).down germ.support
                (germ.compressibleSupport_of_not_distinguishing shorter neutral.2),
            fun germ => germ.not_lengthChanging_iff,
            fun _increment _base _copies _length positive overlapping lower upper
                accepted =>
              Graph.ColdCorridor.exists_not_survivesSmear_of_mem_interval
                positive overlapping lower upper accepted,
            fun _increment _base _exponent _residue positive small reached
                congruent accepted =>
              Graph.ColdCorridor.exists_not_survivesSmear_of_pow_congruent
                positive small reached congruent accepted,
            fun _increment _base _nonzero wide criterion =>
              Graph.ColdCorridor.exists_hit_of_orderOf_lt wide criterion,
            fun _transient _exponent _odd past =>
              Graph.ColdCorridor.pow_mod_of_le past⟩⟩
        .nil)

/-! ## Nodes `[154]`--`[157]`: the four first-failure producers and the routing

`def:cold-corridor-first-failure`'s five alternatives and
`lem:cold-corridor-first-failure`'s five routings.  Each row commits the clause
its own node owns, and each reads exactly the ledger facts the manuscript's
proof spends -- node `[1]`'s target avoidance for (F1), node `[14]`'s
uncompressibility for (F3), and nothing at all for (F2), (F4) and the existence
half, which are theorems about the corridor and the registered signature. -/

/-- **Node `[154]`, `[155]`: the (F1) producer.**

An (F1) completion is a closed walk of the object built from the entry stub, the
corridor prefix, the return adjacency and the window segment; if it is a cycle
of accepted length then the selected object has an accepted cycle, which node
`[1]` denies.  So (F1) never occurs. -/
@[reducible] noncomputable def coldFailureCycleRow :
    AtomicStrategy (Input BranchState Presentation presentation data) :=
  factOnly `Hypostructure.Graph.Strategy.Spine.coldFailureCycle
    (rowManifest (K .selection) (K .coldFailureCycle) (by simp))
    (fun inputs =>
      .cons (key := K .coldFailureCycle)
        ⟨
          (fun _windows _component corridor _order window segment failure =>
            (inputs.get (K .selection)).down.1
              (Graph.ColdCorridor.Corridor.hasCycleWithLength_of_firstFailureCycle
                failure))⟩
        .nil)

/-- **Node `[154]`, `[156]`: the (F2) producer.**

Both directions of `lem:context-universality` at the corridor.  An (F2)
discrepancy -- same cold corridor state, different target response against some
compatible outside context -- denies target-completeness of the identification
in every immutable profile fibre; and with the discrepancy excluded, two
prefixes carrying the same state are context-equivalent, which is what the local
replacement of `lem:cold-same-interface-table` consumes.

The row reads nothing: both are theorems about the corridor's own presentation,
already proved when the cut-state was retained. -/
@[reducible] noncomputable def coldFailureDefectRow :
    AtomicStrategy (Input BranchState Presentation presentation data) :=
  factOnly `Hypostructure.Graph.Strategy.Spine.coldFailureDefect
    (rowManifest (K .coldCorridorState) (K .coldFailureDefect) (by simp))
    (fun inputs =>
      .cons (key := K .coldFailureDefect)
        ⟨
          (fun _windows _component _corridor _presentation _index _boundary
              _carrier _left _right =>
            ⟨fun _Profile _profile failure =>
                Graph.ColdCorridor.Corridor.not_targetComplete_of_firstFailureDefect
                  failure,
              fun excluded same =>
                Graph.ColdCorridor.Corridor.contextEquivalent_of_not_firstFailureDefect
                  excluded same⟩)⟩
        .nil)

/-- **Node `[154]`, `[157]`: the (F3) producer.**

An (F3) pair names an earlier prefix whose own boundary piece is a strictly
smaller proper representative of a later one, with the boundary-degree profile
preserved and the target response equal against every outside context.  That is
a target-complete compression of the later prefix's proper support, and node
`[14]`'s `cor:uncompressible` forbids it.  So (F3) never occurs. -/
@[reducible] noncomputable def coldFailureCompressionRow :
    AtomicStrategy (Input BranchState Presentation presentation data) :=
  factOnly `Hypostructure.Graph.Strategy.Spine.coldFailureCompression
    (rowManifest (K .uncompressible) (K .coldFailureCompression) (by simp))
    (fun inputs =>
      .cons (key := K .coldFailureCompression)
        ⟨
          (fun _windows _component _corridor _presentation _index _support =>
            Graph.ColdCorridor.Corridor.FirstFailureCompression.not_occurs
              (inputs.get (K .uncompressible)).down)⟩
        .nil)

/-- **Node `[154]`, `[156]`: the (F4) producer and its handoff exit.**

A corridor that first enters the declared handoff interfaces already recorded in
the incoming ledger reaches one such support.  Nothing is closed at the
corridor.  The handoff predicate is quantified, so no row manufactures a
handoff object and none is empty by construction. -/
@[reducible] noncomputable def coldFailureHandoffRow :
    AtomicStrategy (Input BranchState Presentation presentation data) :=
  factOnly `Hypostructure.Graph.Strategy.Spine.coldFailureHandoff
    (rowManifest (K .coldCorridorState) (K .coldFailureHandoff) (by simp))
    (fun inputs =>
      .cons (key := K .coldFailureHandoff)
        ⟨
          (fun _windows _component _corridor _handoff _segment failure =>
            Graph.ColdCorridor.Corridor.handoff_mem failure)⟩
        .nil)

/-- **Node `[154]`: the classified state.**

`lem:cold-corridor-first-failure`'s existence half, with the two ledgers it is
counted against.

The existence proof is the manuscript's dichotomy, not a definition: either the
corridor reaches its successor stub inside `Q_cold` states, or `Q_cold + 1`
states are read and two are equal by the pigeonhole on `Q_cold`.  (F5) is
therefore not the complement of the other four clauses, and "a first failure
always exists" is not a tautology.

Beside it the row commits `M_cold`'s bound on the first-failure cold exchange,
`def:cold-window-ledger`'s partition `𝒫 = 𝒫_hot ⊔ 𝒫_cold`, and
`lem:cold-window-stub-excess` in subtraction-free form, with `b(P)` read off the
registered baseline and window order. -/
@[reducible] noncomputable def coldFailureRoutingRow :
    AtomicStrategy (Input BranchState Presentation presentation data) :=
  factOnly `Hypostructure.Graph.Strategy.Spine.coldFailureRouting
    (rowManifest (K .coldCorridorState) (K .coldFailureRouting) (by simp))
    (fun inputs =>
      let _state := inputs.get (K .coldCorridorState)
      .cons (key := K .coldFailureRouting)
        ⟨fun _windows _component corridor presentation index injective =>
          Graph.ColdCorridor.Corridor.exists_firstFailure corridor
            presentation index injective⟩
        .nil)

@[reducible] noncomputable def coldExchangeBoundRow :
    AtomicStrategy (Input BranchState Presentation presentation data) :=
  factOnly `Hypostructure.Graph.Strategy.Spine.coldExchangeBound
    (rowManifest (K .coldFailureRouting) (K .coldExchangeBound) (by simp))
    (fun inputs =>
      let _routing := inputs.get (K .coldFailureRouting)
      .cons (key := K .coldExchangeBound)
        ⟨fun _windows _component corridor terminal =>
          Graph.ColdCorridor.Corridor.exchange_card_le corridor terminal⟩
        .nil)

@[reducible] noncomputable def coldWindowLedgerSplitRow :
    AtomicStrategy (Input BranchState Presentation presentation data) :=
  factOnly `Hypostructure.Graph.Strategy.Spine.coldWindowLedgerSplit
    (sourceFreeManifest (K .coldWindowLedgerSplit))
    (fun _inputs =>
      .cons (key := K .coldWindowLedgerSplit)
        ⟨fun _Window _Coordinate _decWindow _decCoordinate retained
            packageLength packing =>
          Graph.ColdCorridor.coldCount_add_hotCount retained packageLength
            packing⟩
        .nil)

@[reducible] noncomputable def coldHotFailureMassRow :
    AtomicStrategy (Input BranchState Presentation presentation data) :=
  factOnly `Hypostructure.Graph.Strategy.Spine.coldHotFailureMass
    (rowManifest (K .coldWindowLedgerSplit) (K .coldHotFailureMass) (by simp))
    (fun inputs =>
      let _split := inputs.get (K .coldWindowLedgerSplit)
      .cons (key := K .coldHotFailureMass)
        ⟨fun hotRate skeletonRate order slack hotCount coldCount packing
            partition hotBound =>
          Graph.ColdCorridor.hotFailure_coldMass hotRate skeletonRate order
            slack hotCount coldCount packing partition hotBound⟩
        .nil)

@[reducible] noncomputable def coldSelectedBranchExcessRow :
    AtomicStrategy (Input BranchState Presentation presentation data) :=
  factOnly `Hypostructure.Graph.Strategy.Spine.coldSelectedBranchExcess
    (sourceFreeManifest (K .coldSelectedBranchExcess))
    (fun _inputs =>
      .cons (key := K .coldSelectedBranchExcess)
        ⟨fun _Stub stubs =>
          Graph.ColdCorridor.selectedBranchExcess_length stubs⟩
        .nil)

@[reducible] noncomputable def coldAmbientCubicStubExcessRow :
    AtomicStrategy (Input BranchState Presentation presentation data) :=
  factOnly `Hypostructure.Graph.Strategy.Spine.coldAmbientCubicStubExcess
    (rowManifest (K .coldSelectedBranchExcess) (K .coldAmbientCubicStubExcess)
      (by simp))
    (fun inputs =>
      let _selected := inputs.get (K .coldSelectedBranchExcess)
      .cons (key := K .coldAmbientCubicStubExcess)
        ⟨fun _cubicCount _coldCount _nonCubicBound split =>
          Graph.ColdCorridor.branchExcess_ge_of_cubic _ _ _ _ split⟩
        .nil)

/-! ## Nodes `[153]`--`[157]`: the dispatch arms and the branch closure

Rows 57--61.  The manuscript's cold branch ends by *closing*, not by returning a
retained scan, and these three rows are what makes that a theorem: the (F4) arm
transfers through a support predicate already supplied by the ledger, the (F5)
arm is unreachable because the extraction always produces a germ, and no
separate cold-branch record is introduced. -/

/-- **Node `[156]`: the (F4) dispatch arm.**

The corridor reached a declared interface already recorded in the incoming
ledger, and the charge goes there.  The ledger predicate is quantified, so the
arm cannot be discharged by an emptiness manufactured at a call site. -/
@[reducible] noncomputable def coldHandoffTransferRow :
    AtomicStrategy (Input BranchState Presentation presentation data) :=
  factOnly `Hypostructure.Graph.Strategy.Spine.coldHandoffTransfer
    (rowManifest (K .coldFailureHandoff) (K .coldHandoffTransfer) (by simp))
    (fun inputs =>
      .cons (key := K .coldHandoffTransfer)
        ⟨
          (fun _windows _component _corridor _handoff _segment failure =>
            Graph.ColdCorridor.Corridor.handoff_mem failure)⟩
        .nil)

/-- **Nodes `[153]`, `[154]`: the (F5) arm.**

This row commits the local F5 extraction on the current residual.  It reads the
first-failure dichotomy from `coldFailureRouting`; the extraction itself is over
actual current-object bounded germs, with overlap tested on their literal
supports and the disjoint family existentially internal to the fact. -/
@[reducible] noncomputable def coldGermExtractionRow :
    AtomicStrategy (Input BranchState Presentation presentation data) :=
  factOnly `Hypostructure.Graph.Strategy.Spine.coldGermExtraction
    { Requires := [K .coldFailureRouting, K .coldExchangeBound,
        K .coldAmbientCubicStubExcess]
      Produces := [K .coldGermExtraction]
      requiresUnique := by simp
      producesUnique := by simp
      producesNonempty := by simp }
    (fun inputs =>
      let _routing := inputs.get (K .coldFailureRouting)
      let _exchange := inputs.get (K .coldExchangeBound)
      let _stubExcess := inputs.get (K .coldAmbientCubicStubExcess)
      .cons (key := K .coldGermExtraction)
        ⟨Graph.ColdCorridor.coldGermExtractionLocal⟩
        .nil)

@[reducible] noncomputable def coldPositiveGermRow :
    AtomicStrategy (Input BranchState Presentation presentation data) :=
  factOnly `Hypostructure.Graph.Strategy.Spine.coldPositiveGerm
    { Requires := [K .coldHotFailureMass, K .coldAmbientCubicStubExcess,
        K .coldGermExtraction]
      Produces := [K .coldPositiveGerm]
      requiresUnique := by simp
      producesUnique := by simp
      producesNonempty := by simp }
    (fun inputs =>
      let _mass := inputs.get (K .coldHotFailureMass)
      let _stubExcess := inputs.get (K .coldAmbientCubicStubExcess)
      let _extraction := inputs.get (K .coldGermExtraction)
      .cons (key := K .coldPositiveGerm)
        ⟨fun Germ decGerm candidates disjointFamily perWindow coldCount
            branchExcess denominator slack stubExcess candidateLoss cover
            linear =>
          letI : DecidableEq Germ := decGerm
          Graph.ColdCorridor.coldGerm_positive perWindow coldCount
            branchExcess denominator slack stubExcess candidateLoss cover
            linear⟩
        .nil)

/-- **Nodes `[145]`--`[157]`: `thm:cold-branch-quantitative-closure`.**

The row reads G1, G2, and G3 from the incoming ledger and commits the remaining
cold germ routing fact: every oriented length-changing bounded germ is routed
through the target-defect arm.  This fact is published directly on the canonical
ledger; no branch record, terminal payload, or retired routing object is used. -/
@[reducible] noncomputable def coldGermRoutedRow :
    AtomicStrategy (Input BranchState Presentation presentation data) :=
  factOnly `Hypostructure.Graph.Strategy.Spine.coldGermRouted
    { Requires := [K .coldGermRealized, K .coldGermDistinguished,
        K .coldGermSilent]
      Produces := [K .coldGermRouted]
      requiresUnique := by simp
      producesUnique := by simp
      producesNonempty := by simp }
    (fun inputs =>
      let notRealizing := (inputs.get (K .coldGermRealized)).down.1
      let targetDefect := (inputs.get (K .coldGermDistinguished)).down
      let notSilent := (inputs.get (K .coldGermSilent)).down.1
      .cons (key := K .coldGermRouted)
        ⟨fun germ shorter =>
          let distinguishing :=
            Graph.ColdCorridor.boundedGerm_not_survives notRealizing notSilent
              germ shorter
          ⟨distinguishing, fun Profile profile =>
            targetDefect germ Profile profile distinguishing⟩⟩
        .nil)

/-- **Node `[157]`: the cold oval closes on the current residual.**

The final row reads the length-changing route and the finite same-interface
table by key, and it also reads the local extraction fact that turns a terminal
candidate family into a positive extracted subfamily.  It does not transport a
corridor, a germ family, or a side classifier. -/
@[reducible] noncomputable def coldBranchClosedRow :
    AtomicStrategy (Input BranchState Presentation presentation data) :=
  factOnly `Hypostructure.Graph.Strategy.Spine.coldBranchClosed
    { Requires := [K .coldPositiveGerm, K .coldGermExtraction, K .coldGermRouted,
        K .coldSameInterfaceTable]
      Produces := [K .coldBranchClosed]
      requiresUnique := by simp
      producesUnique := by simp
      producesNonempty := by simp }
    (fun inputs =>
      let _positive := inputs.get (K .coldPositiveGerm)
      let extraction := (inputs.get (K .coldGermExtraction)).down
      let routed := (inputs.get (K .coldGermRouted)).down
      let table := (inputs.get (K .coldSameInterfaceTable)).down
      .cons (key := K .coldBranchClosed)
        ⟨Graph.ColdCorridor.noTerminalColdResidual_of_routing
          (extraction := extraction) (routed := routed) (table := table.1)
          (selfReturns := table.2.1)⟩
        .nil)

end Hypostructure.Graph.Strategy.Spine
