import Hypostructure.Graph.Strategy.HomogeneousBottleneckRows.Basic
import Hypostructure.Graph.Strategy.HomogeneousBottleneckRows.WindowOverloadClass
import Hypostructure.Graph.Strategy.HomogeneousBottleneckRows.RoleFibrePartition
import Hypostructure.Graph.Strategy.HomogeneousBottleneckRows.PressureSpineSurplusEstimate
import Hypostructure.Graph.Strategy.HomogeneousBottleneckRows.HomogeneousBottleneckAudit
import Hypostructure.Graph.Strategy.HomogeneousBottleneckRows.SameTokenBottleneckRouting
import Hypostructure.Graph.Strategy.HomogeneousBottleneckRows.SameTokenTypeBFanEntry
import Hypostructure.Graph.Strategy.HomogeneousBottleneckRows.HomogeneousCapsClose
import Hypostructure.Graph.Strategy.HomogeneousBottleneckRows.SparseSurplusExit
import Hypostructure.Graph.Strategy.HomogeneousBottleneckRows.FreePairEntropy
import Hypostructure.Graph.Strategy.HomogeneousBottleneckRows.FreePairCoupledExcess
import Hypostructure.Graph.Strategy.HomogeneousBottleneckRows.BlockedPairEntropy
import Hypostructure.Graph.Strategy.HomogeneousBottleneckRows.PairOverlapFirstFailure
import Hypostructure.Graph.Strategy.HomogeneousBottleneckRows.PairOverlapSystem
import Hypostructure.Graph.Strategy.HomogeneousBottleneckRows.PairFailureOverlap
import Hypostructure.Graph.Strategy.HomogeneousBottleneckRows.PairSystemOutcome
import Hypostructure.Graph.Strategy.HomogeneousBottleneckRows.PairPowerOfTwoCycle
import Hypostructure.Graph.Strategy.HomogeneousBottleneckRows.FibrePressure

/-!
# The homogeneous-bottleneck and pair-overlap rows

Aggregator of the per-row modules under `HomogeneousBottleneckRows/`.  Each
module holds one paper row, decision, or instance group on the literal current
`ExactLedger`; importers use the specific module they consume.
-/
