/-!
DEPRECATED: migrated to canonical CT composition strategy
(CT6 -> CT5 -> CT14 -> CT1).
This detached feature executor is retained only as a parity oracle until
its CT-ledger equivalence theorem is kernel-checked.  It must not be
registered or executed by the framework.
-/
import Mathlib.Data.List.Duplicate
import Hypostructure.Graph.Strategy.Official.Features.DegreeSurplusLedger
import Hypostructure.Graph.Strategy.Official.Features.DeletionFanIncidence

/-!
# High-centre fan accounting and closure

This Graph adapter consumes the literal residual produced by edge-deletion
criticality.  It derives every centre, port, outside incidence, surplus unit,
carrier collision, and branch test from that residual and the ambient graph.

The engine has no application callback and no authored route.  A repeated
carrier produces the first route core in the graph's declared vertex order.
If all carriers are disjoint, finite cardinality accounting either closes an
impossible over-budget branch or returns the exact unresolved budget ledger
needed by a later graph inequality.
-/

namespace Hypostructure.Graph.Strategy.Official.Features.HighCenterFanClosure

open Hypostructure.Graph
open DeletionFanIncidence

universe u v

variable
    {Baseline : FiniteObject.{u} → Prop}
    {BranchState : FiniteObject.{u} → Type v}
    {Target : FiniteObject.{u} → Prop}
    {profile : DeletionCriticalityProfile Baseline}
    {ctx : Core.MinimalCounterexampleContext
      (problem Baseline BranchState) Target
      (lexicographicProgress Baseline BranchState)}

/-- One literal fan incidence together with one of its outside carriers. -/
structure CarrierClaim
    (profile : DeletionCriticalityProfile Baseline)
    (object : FiniteObject.{u}) where
  incidence : PortIncidence profile object
  carrier : object.Vertex
  carrier_mem : carrier ∈ incidence.outside

/-- Claims are generated by flattening the literal outside-incidence rows.
No carrier or multiplicity can be supplied by a proof author. -/
def carrierClaims
    (residual : DeletionFanIncidence.Residual profile ctx) :
    List (CarrierClaim profile ctx.G) :=
  residual.incidences.flatMap fun incidence =>
    incidence.outside.attach.map fun carrier =>
      ⟨incidence, carrier.1, carrier.2⟩

def carriers
    (residual : DeletionFanIncidence.Residual profile ctx) :
    List ctx.G.Vertex :=
  (carrierClaims residual).map CarrierClaim.carrier

/-- Incidences carrying at least one outside certificate.  Presence is tested
by the engine against the generated outside row. -/
def certifiedIncidences
    (residual : DeletionFanIncidence.Residual profile ctx) :
    List (PortIncidence profile ctx.G) :=
  residual.incidences.filter fun incidence =>
    decide (incidence.outside ≠ [])

/-- Exact fan mass, retaining multiplicity. -/
def fanMass
    (residual : DeletionFanIncidence.Residual profile ctx) : Nat :=
  (carriers residual).length

/-- Degree-surplus units at the generated high centres. -/
def centerSurplusMass
    (residual : DeletionFanIncidence.Residual profile ctx) : Nat :=
  (residual.centers.map fun row =>
    ctx.G.degree row.center - profile.threshold).sum

theorem centerSurplusMass_eq_excess_ports
    (residual : DeletionFanIncidence.Residual profile ctx) :
    centerSurplusMass residual =
      (residual.centers.flatMap HighCenterRow.excess).length := by
  simp only [centerSurplusMass, List.length_flatMap, HighCenterRow.excess_length]

/-- Carriers occurring at least twice, in the ambient graph's canonical
vertex order.  This is the disjoint-carrier test and the overlap schedule. -/
def overlapCarriers
    (residual : DeletionFanIncidence.Residual profile ctx) :
    List ctx.G.Vertex := by
  letI : DecidableEq ctx.G.Vertex := ctx.G.vertices.decEq
  exact ctx.G.orderedVertices.filter fun carrier =>
    decide (List.Duplicate carrier (carriers residual))

/-- The first overlap is selected by the framework's canonical graph order. -/
def firstOverlap?
    (residual : DeletionFanIncidence.Residual profile ctx) :
    Option ctx.G.Vertex :=
  (overlapCarriers residual).head?

/-- The stronger two-carrier test: at least two distinct repeated carriers
occur.  No special numerical parameter is accepted. -/
def hasDisjointCarrierPair
    (residual : DeletionFanIncidence.Residual profile ctx) : Bool :=
  decide (2 ≤ (overlapCarriers residual).length)

/-- The local two-incidence test at a carrier. -/
def hasBinaryOverlap
    (residual : DeletionFanIncidence.Residual profile ctx)
    (carrier : ctx.G.Vertex) : Bool := by
  letI : DecidableEq ctx.G.Vertex := ctx.G.vertices.decEq
  exact decide (List.Duplicate carrier (carriers residual))

/-- One exact accounting ledger. -/
structure Ledger
    (residual : DeletionFanIncidence.Residual profile ctx) where
  deletion : DeletionFanIncidence.Residual profile ctx
  deletion_eq : deletion = residual
  surplus : DegreeSurplusLedger.Ledger ctx.G
    { degree := profile.threshold
      lower := fun vertex => by
        exact (profile.degreeLowerBound ctx.baseline)
          |>.trans (ctx.G.minDegree_le_degree vertex) }
  claims : List (CarrierClaim profile ctx.G)
  claims_eq : claims = carrierClaims residual
  certified : List (PortIncidence profile ctx.G)
  certified_eq : certified = certifiedIncidences residual
  overlaps : List ctx.G.Vertex
  overlaps_eq : overlaps = overlapCarriers residual
  mass : Nat
  mass_eq : mass = fanMass residual
  surplusMass : Nat
  surplusMass_eq : surplusMass = centerSurplusMass residual
  binaryOverlap : Bool
  binaryOverlap_eq : binaryOverlap =
    decide (overlaps.head?.isSome)
  disjointCarrierPair : Bool
  disjointCarrierPair_eq : disjointCarrierPair =
    decide (2 ≤ overlaps.length)

def deriveLedger
    (residual : DeletionFanIncidence.Residual profile ctx) :
    Ledger residual where
  deletion := residual
  deletion_eq := rfl
  surplus := DegreeSurplusLedger.derive ctx.G
    { degree := profile.threshold
      lower := fun vertex => by
        exact (profile.degreeLowerBound ctx.baseline)
          |>.trans (ctx.G.minDegree_le_degree vertex) }
  claims := carrierClaims residual
  claims_eq := rfl
  certified := certifiedIncidences residual
  certified_eq := rfl
  overlaps := overlapCarriers residual
  overlaps_eq := rfl
  mass := fanMass residual
  mass_eq := rfl
  surplusMass := centerSurplusMass residual
  surplusMass_eq := rfl
  binaryOverlap := decide (firstOverlap? residual).isSome
  binaryOverlap_eq := rfl
  disjointCarrierPair := hasDisjointCarrierPair residual
  disjointCarrierPair_eq := rfl

/-- A cardinal budget contradiction, derived only after the carrier list is
proved injective and its computed mass exceeds the ambient finite carrier
space. -/
structure ClosedBudgetContradiction
    (residual : DeletionFanIncidence.Residual profile ctx)
    (ledger : Ledger residual) : Prop where
  carriersNodup : (carriers residual).Nodup
  overBudget : ctx.G.vertexCount < ledger.mass
  contradiction : False

/-- The canonical overlap core handed to the next routing strategy. -/
structure RouteCoreResidual
    (residual : DeletionFanIncidence.Residual profile ctx)
    (ledger : Ledger residual) where
  carrier : ctx.G.Vertex
  carrier_eq : firstOverlap? residual = some carrier
  repeated : List.Duplicate carrier (carriers residual)
  binaryOverlap : hasBinaryOverlap residual carrier = true
  hasSecondDisjointCarrier : Bool
  hasSecondDisjointCarrier_eq :
    hasSecondDisjointCarrier = hasDisjointCarrierPair residual

/-- Honest residual when disjoint carrier accounting is within the ambient
budget and a separate graph inequality is required to continue. -/
structure UnresolvedBudgetResidual
    (residual : DeletionFanIncidence.Residual profile ctx)
    (ledger : Ledger residual) where
  carriersNodup : (carriers residual).Nodup
  withinBudget : ledger.mass ≤ ctx.G.vertexCount
  missingFinalInequality :
    ledger.mass ≤ ctx.G.vertexCount

inductive Terminal
    (residual : DeletionFanIncidence.Residual profile ctx)
    (ledger : Ledger residual) : Type (max u v) where
  | closedBudget : ClosedBudgetContradiction residual ledger → Terminal residual ledger
  | routeCore : RouteCoreResidual residual ledger → Terminal residual ledger
  | unresolved : UnresolvedBudgetResidual residual ledger → Terminal residual ledger

private theorem vertexCount_eq_card (object : FiniteObject.{u}) :
    object.vertexCount =
      @Fintype.card object.Vertex
        (@FinEnum.instFintype _ object.vertices) := by
  change object.vertices.card =
    @Fintype.card object.Vertex
      (@FinEnum.instFintype _ object.vertices)
  exact @FinEnum.card_eq_fintypeCard _ object.vertices
    (@FinEnum.instFintype _ object.vertices)

private theorem firstOverlap_of_not_nodup
    (residual : DeletionFanIncidence.Residual profile ctx)
    (notNodup : ¬(carriers residual).Nodup) :
    ∃ carrier, firstOverlap? residual = some carrier ∧
      List.Duplicate carrier (carriers residual) := by
  letI : DecidableEq ctx.G.Vertex := ctx.G.vertices.decEq
  obtain ⟨carrier, repeated⟩ :=
    List.exists_duplicate_iff_not_nodup.mpr notNodup
  have carrier_mem : carrier ∈ ctx.G.orderedVertices :=
    ctx.G.mem_orderedVertices carrier
  have overlap_mem : carrier ∈ overlapCarriers residual := by
    simp [overlapCarriers, carrier_mem, repeated]
  have nonempty : overlapCarriers residual ≠ [] := by
    intro empty
    simpa [empty] using overlap_mem
  obtain ⟨first, tail, first_eq⟩ := List.exists_cons_of_ne_nil nonempty
  refine ⟨first, ?_, ?_⟩
  · simp [firstOverlap?, first_eq]
  · have : first ∈ overlapCarriers residual := by simp [first_eq]
    simpa [overlapCarriers] using this

/-- Framework-owned execution.  The only branch tests are list nodup and the
literal finite carrier budget. -/
noncomputable def execute
    (residual : DeletionFanIncidence.Residual profile ctx) :
    let ledger := deriveLedger residual
    Terminal residual ledger := by
  let ledger := deriveLedger residual
  by_cases nodup : (carriers residual).Nodup
  · by_cases exceeds : ctx.G.vertexCount < ledger.mass
    · exact Terminal.closedBudget {
        carriersNodup := nodup
        overBudget := exceeds
        contradiction := by
          letI : FinEnum ctx.G.Vertex := ctx.G.vertices
          have bound : (carriers residual).length ≤
              Fintype.card ctx.G.Vertex :=
            nodup.length_le_card
          rw [← vertexCount_eq_card] at bound
          simpa [ledger, deriveLedger, fanMass] using
            (Nat.not_lt_of_ge bound exceeds) }
    · exact Terminal.unresolved {
        carriersNodup := nodup
        withinBudget := by
          simpa [ledger, deriveLedger, fanMass] using Nat.le_of_not_gt exceeds
        missingFinalInequality := by
          simpa [ledger, deriveLedger, fanMass] using Nat.le_of_not_gt exceeds }
  · let carrier := Classical.choose
      (firstOverlap_of_not_nodup residual nodup)
    have selected := Classical.choose_spec
      (firstOverlap_of_not_nodup residual nodup)
    exact Terminal.routeCore {
      carrier := carrier
      carrier_eq := selected.1
      repeated := selected.2
      binaryOverlap := by
        letI : DecidableEq ctx.G.Vertex := ctx.G.vertices.decEq
        change decide (List.Duplicate carrier (carriers residual)) = true
        exact decide_eq_true selected.2
      hasSecondDisjointCarrier := hasDisjointCarrierPair residual
      hasSecondDisjointCarrier_eq := rfl }

/-- Exact static work derived from generated schedule sizes. -/
def work
    (residual : DeletionFanIncidence.Residual profile ctx) : Nat :=
  residual.incidences.length +
    (carrierClaims residual).length +
    ctx.G.orderedVertices.length

end Hypostructure.Graph.Strategy.Official.Features.HighCenterFanClosure
