import Hypostructure.PDE.Object
import Hypostructure.PDE.NoSingularityTarget
import Hypostructure.PDE.LocalSolution
import Hypostructure.PDE.FrameInvariance
import Hypostructure.PDE.Atlas
import Hypostructure.PDE.Equation
import Hypostructure.PDE.Model
import Hypostructure.PDE.External
import Hypostructure.PDE.Finite
import Hypostructure.PDE.FastTrack
import Hypostructure.PDE.Representation
import Hypostructure.PDE.Isomorphism
import Hypostructure.PDE.SupportCharge
import Hypostructure.PDE.OneThreeRepair
import Hypostructure.PDE.Progress
import Hypostructure.PDE.Obstruction
import Hypostructure.PDE.SupportComponents
import Hypostructure.PDE.Observable
import Hypostructure.PDE.Response
import Hypostructure.PDE.Boundary
import Hypostructure.PDE.BoundaryOverlap
import Hypostructure.PDE.AtomResponse
import Hypostructure.PDE.Target
import Hypostructure.PDE.Minimality
import Hypostructure.PDE.Deletion
import Hypostructure.PDE.DeletionCriticality
import Hypostructure.PDE.RootedReturn
import Hypostructure.PDE.InducedPath
import Hypostructure.PDE.InducedPathMaximalPacking
import Hypostructure.PDE.InducedPathWindowLedger
import Hypostructure.PDE.InducedPathCold
import Hypostructure.PDE.InducedPathColdQuery
import Hypostructure.PDE.TargetClosure
import Hypostructure.PDE.Coordinate
import Hypostructure.PDE.Focus
import Hypostructure.PDE.LocalTail
import Hypostructure.PDE.EllipticLocalTail
import Hypostructure.PDE.ParabolicAtlas
import Hypostructure.PDE.SpacetimeCoordinates
import Hypostructure.PDE.EuclideanParabolicAtlas
import Hypostructure.PDE.Solution.SchwartzSobolev
import Hypostructure.PDE.Solution.BalanceWindowCertificate
import Hypostructure.PDE.Solution.QuotientRecoveryData
import Hypostructure.PDE.Localization.PlacementOfBaseline
import Hypostructure.PDE.Localization.ComponentPlacement
import Hypostructure.PDE.TailContinuation
import Hypostructure.PDE.FastTrack.Signature
import Hypostructure.PDE.GeneratorForm
import Hypostructure.PDE.Quotient
import Hypostructure.PDE.DirectResistance
import Hypostructure.PDE.StructuralGradient
import Hypostructure.PDE.FastTrack.DirectedExhaustiveness
import Hypostructure.PDE.FastTrack.DefectRouting
import Hypostructure.PDE.FastTrack.DefectRoutingAlignment
import Hypostructure.PDE.FastTrack.TargetCompactification
import Hypostructure.PDE.FastTrack.CapacityProfile
import Hypostructure.PDE.FastTrack.ExactResponseCoverage
import Hypostructure.PDE.FastTrack.ProfileFamily
import Hypostructure.PDE.FastTrack.BoundaryRepair
import Hypostructure.PDE.FastTrack.ConservativeCarrier
import Hypostructure.PDE.FastTrack.EllipticConstraintTail
import Hypostructure.PDE.FastTrack.FluxRadius
import Hypostructure.PDE.FastTrack.Saturation
import Hypostructure.PDE.FastTrack.WindowSchedule
import Hypostructure.PDE.Budget
import Hypostructure.PDE.BudgetOverload
import Hypostructure.PDE.AssignedSupportCharge
import Hypostructure.PDE.Theorems
import Hypostructure.PDE.Contract
import Hypostructure.PDE.CT3
import Hypostructure.PDE.CT1
import Hypostructure.PDE.CT2
import Hypostructure.PDE.CT4
import Hypostructure.PDE.CT5
import Hypostructure.PDE.CT6
import Hypostructure.PDE.CT7
import Hypostructure.PDE.CT8
import Hypostructure.PDE.CT9
import Hypostructure.PDE.CT10
import Hypostructure.PDE.CT11
import Hypostructure.PDE.CT12
import Hypostructure.PDE.CT13
import Hypostructure.PDE.CT14
import Hypostructure.PDE.CT15
import Hypostructure.PDE.CT16
import Hypostructure.PDE.CT17
import Hypostructure.PDE.Strategy
import Hypostructure.PDE.Strategy.LocalClosureAlgebra
import Hypostructure.PDE.Strategy.LocalRegularityChain
import Hypostructure.PDE.Strategy.LocalBalanceClosure
import Hypostructure.PDE.Distribution.Local
import Hypostructure.PDE.Solution.Interval
import Hypostructure.PDE.Model.Interval
import Hypostructure.PDE.Distribution.OfFunction
import Hypostructure.PDE.Distribution.SmoothRepresentative
import Hypostructure.PDE.Distribution.ComponentBalance
import Hypostructure.PDE.Solution.Bessel
import Hypostructure.PDE.Localization.Recenter
import Hypostructure.PDE.Localization.Cutoff
import Hypostructure.PDE.Solution.Potential
import Hypostructure.PDE.Solution.RadialKernel
import Hypostructure.PDE.Solution.EllipticRegularity
import Hypostructure.PDE.Localization.Tempered
import Hypostructure.PDE.Vorticity
import Hypostructure.PDE.DivCurl
import Hypostructure.PDE.HeatSmoothing
import Hypostructure.PDE.GlobalFromLocal
import Hypostructure.PDE.Solution.Newtonian
import Hypostructure.PDE.Solution.InteriorRegularity
import Hypostructure.PDE.Solution.LocalEmbedding
import Hypostructure.PDE.Solution.ParabolicRegularity
import Hypostructure.PDE.Solution.WindowCertificate
import Hypostructure.PDE.Distribution.CurlCalculus
import Hypostructure.PDE.Distribution.Multiplier
import Hypostructure.PDE.Distribution.Recovery
import Hypostructure.PDE.Model.Bessel
import Hypostructure.PDE.Localization.TemperedBridge
import Hypostructure.PDE.Localization.WindowAgreement
import Hypostructure.PDE.Localization.BalanceTransport
import Hypostructure.PDE.Solution.SliceRestriction
import Hypostructure.PDE.Solution.ScaleRecombination
import Hypostructure.PDE.Solution.HarmonicKernelSmoothing
import Hypostructure.PDE.Solution.RepresentativeGluing
import Hypostructure.PDE.Solution.SliceInversionRegularity
import Hypostructure.PDE.Solution.PressureNormalization
import Hypostructure.PDE.Singularity
import Hypostructure.PDE.ForcingNormalization
import Hypostructure.PDE.DivCurlPotential
import Hypostructure.PDE.Solution.QuotientVelocityRegularity
import Hypostructure.PDE.Localization.RegularityTransport
import Hypostructure.PDE.Localization.ParabolicRecentering
import Hypostructure.PDE.Strategy.BalancedRegularity
import Hypostructure.PDE.Strategy.RegularityStratification
import Hypostructure.PDE.Strategy.ScaleThresholdDichotomy
import Hypostructure.PDE.Strategy.BalanceBaseline
import Hypostructure.PDE.Strategy.RegularityRegistry
import Hypostructure.PDE.Strategy.Registry.BarrierAndCapacity
import Hypostructure.PDE.Strategy.Registry.FibrePressure
import Hypostructure.PDE.Strategy.Registry.PackingNormalization
import Hypostructure.PDE.Strategy.Registry.RankAndCold
import Hypostructure.PDE.Strategy.Registry.CounterexampleReduction
import Hypostructure.PDE.Strategy.Official.SealedDag

/-!
# Generic PDE specialization

This barrel intentionally excludes `Hypostructure.PDE.NavierStokes`.  A
domain-independent PDE consumer does not acquire model-specific equations or
constants by importing the specialization API.
-/
