import Hypostructure.Core.Finite.Enumeration
import Hypostructure.Core.Strategy.SupportComplementNormalizationSemantics

/-!
# Residual-indexed boundary-demand accounting semantics

Inert presentation data for the CT4 → CT14 composition implemented in
`BoundaryDemandAccounting.lean`.  The record supplies only the primitive
demand, payer, eligibility, weight, capacity, aggregate, and labelling
semantics.  Core supplies the exact normalized-support ledger published by a
completed `SupportComplementNormalization`, and the exact assigned total
generated by CT4.
-/

namespace Hypostructure.Core.Strategy.BoundaryDemandAccounting

universe uResidual uDemand uPayer uMember uLabel

open Hypostructure.Core.Strategy

namespace FiniteInteraction

universe uItem

/-- Total interaction load from one item into an exact finite schedule. -/
def load {Item : Type uItem} (incidence : Item → Item → Nat)
    (schedule : Core.Finite.Enumeration Item) (item : Item) : Nat :=
  (schedule.values.map (incidence item)).sum

/-- Positive baseline deficiency on an exact finite schedule. -/
def positiveDeficiency {Item : Type uItem} (baseline : Nat)
    (internal : Item → Nat) (schedule : Core.Finite.Enumeration Item) : Nat :=
  (schedule.values.map fun item => baseline - internal item).sum

/-- Total boundary interaction emitted by an exact finite schedule. -/
def boundarySupply {Item : Type uItem} (boundary : Item → Nat)
    (schedule : Core.Finite.Enumeration Item) : Nat :=
  (schedule.values.map boundary).sum

/-- Summed positive deficiency is bounded by the literal boundary supply.

This is the domain-neutral arithmetic used by the sealed CT4 operation.  The
only hypothesis is the pointwise load split supplied by the finite interaction
ledger; no graph, PDE, path order, or paper constant occurs in the theorem. -/
theorem positiveDeficiency_le_boundarySupply
    {Item : Type uItem} (baseline : Nat) (internal boundary : Item → Nat)
    (schedule : Core.Finite.Enumeration Item)
    (minimumLoad : ∀ item ∈ schedule.values,
      baseline ≤ internal item + boundary item) :
    positiveDeficiency baseline internal schedule ≤
      boundarySupply boundary schedule := by
  unfold positiveDeficiency boundarySupply
  apply List.sum_le_sum
  intro item member
  have := minimumLoad item member
  omega

/-- The block-side account is additive over the literal finite block table.
The block table, its order, and its baseline are parameters of the generic
operation; no application constant is embedded in this theorem. -/
theorem sum_boundary_add_internal_eq
    {Block : Type uItem}
    (baseline order : Nat)
    (blocks : Core.Finite.Enumeration Block)
    (boundary internal surplus : Block → Nat)
    (localAccount : ∀ block ∈ blocks.values,
      boundary block + internal block = baseline * order + surplus block) :
    (blocks.values.map boundary).sum +
        (blocks.values.map internal).sum =
      (baseline * order) * blocks.card +
        (blocks.values.map surplus).sum := by
  rw [Core.Finite.Enumeration.card]
  calc
    (blocks.values.map boundary).sum + (blocks.values.map internal).sum =
        (blocks.values.map (fun block => boundary block + internal block)).sum := by
          simp [List.sum_map_add]
    _ = (blocks.values.map (fun block => baseline * order + surplus block)).sum := by
          exact congrArg List.sum (List.map_congr_left localAccount)
    _ = (baseline * order) * blocks.values.length +
          (blocks.values.map surplus).sum := by
          rw [List.sum_map_add]
          simp [List.map_const, Nat.mul_comm]

/-- The surplus-aware ceiling is the nonnegative part of the exact block
account. Consumers use this theorem through the ordinary accumulated ledger;
they never unfold or reconstruct the block schedule. -/
theorem boundary_le_block_baseline_add_surplus
    {Block : Type uItem}
    (baseline order : Nat)
    (blocks : Core.Finite.Enumeration Block)
    (boundary internal surplus : Block → Nat)
    (account :
      (blocks.values.map boundary).sum + (blocks.values.map internal).sum =
        (baseline * order) * blocks.card + (blocks.values.map surplus).sum) :
    (blocks.values.map boundary).sum ≤
      (baseline * order) * blocks.card + (blocks.values.map surplus).sum := by
  omega

/-! Named framework corollaries for the finite interaction obligations used by
the sealed strategy.  They are intentionally expressed only through incoming
finite schedules and ledger equations. -/

theorem deficiency_surplus_split
    {Item : Type uItem} (baseline : Nat) (internal boundary : Item → Nat)
    (schedule : Core.Finite.Enumeration Item) :
    positiveDeficiency baseline internal schedule =
      (schedule.values.map fun item => baseline - internal item).sum := rfl

theorem stub_positive
    {Item : Type uItem} (baseline : Nat) (internal boundary : Item → Nat)
    (schedule : Core.Finite.Enumeration Item)
    (minimumLoad : ∀ item ∈ schedule.values,
      baseline ≤ internal item + boundary item) :
    positiveDeficiency baseline internal schedule ≤
      boundarySupply boundary schedule :=
  positiveDeficiency_le_boundarySupply baseline internal boundary schedule minimumLoad

theorem exact_window_join_identity
    {Block : Type uItem} (baseline order : Nat)
    (blocks : Core.Finite.Enumeration Block)
    (boundary internal surplus : Block → Nat)
    (account : ∀ block ∈ blocks.values,
      boundary block + internal block = baseline * order + surplus block) :
    (blocks.values.map boundary).sum + (blocks.values.map internal).sum =
      (baseline * order) * blocks.card + (blocks.values.map surplus).sum :=
  sum_boundary_add_internal_eq baseline order blocks boundary internal surplus account

theorem surplus_aware_window_stub
    {Block : Type uItem} (baseline order : Nat)
    (blocks : Core.Finite.Enumeration Block)
    (boundary internal surplus : Block → Nat)
    (account :
      (blocks.values.map boundary).sum + (blocks.values.map internal).sum =
        (baseline * order) * blocks.card + (blocks.values.map surplus).sum) :
    (blocks.values.map boundary).sum ≤
      (baseline * order) * blocks.card + (blocks.values.map surplus).sum := by
  exact boundary_le_block_baseline_add_surplus baseline order blocks boundary
    internal surplus account

end FiniteInteraction

/-- The exact supply account published at a boundary-demand node.  All
quantities are finite sums over the predecessor-owned item and block
schedules.  In particular `blockCount` is the number of blocks, not the size
of their union. -/
structure SupplyAccount where
  positiveDeficiency : Nat
  boundarySupply : Nat
  blockBoundarySupply : Nat
  blockInternal : Nat
  blockSurplus : Nat
  blockCount : Nat
  baseline : Nat
  order : Nat
  stubRate : Nat
  deficiency_le_boundary : positiveDeficiency ≤ boundarySupply
  exactBlockAccount :
    blockBoundarySupply + blockInternal =
      (baseline * order) * blockCount + blockSurplus
  boundary_le_ceiling :
    boundarySupply ≤ stubRate * blockCount + blockSurplus
  deficiency_le_ceiling :
    positiveDeficiency ≤
      stubRate * blockCount + blockSurplus

/-- Construct the theorem ledger from the two literal finite schedules and
their primitive interaction laws.  This operation performs no routing and
accepts no advertised conclusion: each published inequality is derived here
from the pointwise load split and the exact additive block account. -/
def SupplyAccount.ofFiniteInteraction
    {Item : Type uDemand} {Block : Type uPayer}
    (baseline order : Nat)
    (items : Core.Finite.Enumeration Item)
    (blocks : Core.Finite.Enumeration Block)
    (internal boundary : Item → Nat)
    (blockBoundary blockInternal blockSurplus : Block → Nat)
    (minimumLoad : ∀ item ∈ items.values,
      baseline ≤ internal item + boundary item)
    (boundaryCovered :
      FiniteInteraction.boundarySupply boundary items ≤
        (blocks.values.map blockBoundary).sum)
    (blockAccount : ∀ block ∈ blocks.values,
      blockBoundary block + blockInternal block =
        baseline * order + blockSurplus block)
    (blockInternalExact : ∀ block ∈ blocks.values,
      blockInternal block = 2 * (order - 1))
    (stubRate : Nat)
    (stubRateExact : stubRate + 2 * (order - 1) = baseline * order) :
    SupplyAccount := by
  let deficiency :=
    FiniteInteraction.positiveDeficiency baseline internal items
  let supply := FiniteInteraction.boundarySupply boundary items
  let blockSupply := (blocks.values.map blockBoundary).sum
  let internalTotal := (blocks.values.map blockInternal).sum
  let surplusTotal := (blocks.values.map blockSurplus).sum
  have lower : deficiency ≤ supply :=
    FiniteInteraction.positiveDeficiency_le_boundarySupply
      baseline internal boundary items minimumLoad
  have account0 := FiniteInteraction.sum_boundary_add_internal_eq
    baseline order blocks blockBoundary blockInternal blockSurplus blockAccount
  have account : blockSupply + internalTotal =
      (baseline * order) * blocks.card + surplusTotal := by
    dsimp [blockSupply, internalTotal, surplusTotal]
    exact account0
  have internalTotalExact :
      internalTotal = (2 * (order - 1)) * blocks.card := by
    rw [Core.Finite.Enumeration.card]
    dsimp [internalTotal]
    calc
      (blocks.values.map blockInternal).sum =
          (blocks.values.map fun _ => 2 * (order - 1)).sum := by
            exact congrArg List.sum
              (List.map_congr_left blockInternalExact)
      _ = (2 * (order - 1)) * blocks.values.length := by
            simp [Nat.mul_comm]
  have rateMul :
      stubRate * blocks.card +
          (2 * (order - 1)) * blocks.card =
        (baseline * order) * blocks.card := by
    calc
      stubRate * blocks.card + (2 * (order - 1)) * blocks.card =
          (stubRate + 2 * (order - 1)) * blocks.card := by
            rw [Nat.add_mul]
      _ = (baseline * order) * blocks.card := by rw [stubRateExact]
  have upper : supply ≤
      stubRate * blocks.card + surplusTotal := by omega
  exact
    { positiveDeficiency := deficiency
      boundarySupply := supply
      blockBoundarySupply := blockSupply
      blockInternal := internalTotal
      blockSurplus := surplusTotal
      blockCount := blocks.card
      baseline := baseline
      order := order
      stubRate := stubRate
      deficiency_le_boundary := lower
      exactBlockAccount := account
      boundary_le_ceiling := upper
      deficiency_le_ceiling := lower.trans upper }

/-- Exact numeric ledger published by one completed boundary accounting.

The last three fields are the window/remainder coordinates of manuscript node
`[29]`.  They are not recomputed here: they are the three counts CT9 already
published on the normalized-support ledger this node reads, copied verbatim
onto the accounting entry so that a consumer downstream of the accounting
boundary -- where the normalization ledger itself no longer travels -- can
still state the node-`[29]` supply account in the manuscript's own variables:

* `ambientCount` is `n`, the ambient item schedule CT9 partitioned;
* `selectedCount` is `|W|`, the part covered by the selected packing (for the
  Erdős–Gyárfás presentation that is `13 p₁₃`, the vertices of the packed
  windows, *not* the number of windows);
* `complementCount` is `|R|`, the normalized remainder.

`memberCapacity` in `BoundaryDemandAccounting.lean` already multiplies the
registered per-member capacity rate by `selectedCount`; these fields publish
the same three numbers rather than a second, independently derived copy. -/
structure Summary where
  demandCount : Nat
  payerCount : Nat
  requiredTotal : Nat
  assignedTotal : Nat
  capacityTotal : Nat
  /-- `n`: CT9's ambient item count on the normalized-support ledger. -/
  ambientCount : Nat
  /-- `|W|`: CT9's selected fibre count on the same ledger. -/
  selectedCount : Nat
  /-- `|R|`: CT9's complementary fibre count on the same ledger. -/
  complementCount : Nat
  deriving DecidableEq, Repr, Inhabited

/-- Residual-owned demand/payer presentation together with the aggregate
members CT14 compares.

Every field is indexed by the residual alone, and the two aggregate
observations are per-member *rates*.  The exact normalized-support ledger is
not a registration field: Core constructs it as a typed ledger query from the
actual producer entry and multiplies the registered capacity rate by its
extensive selected count in the profile, exactly as `FiniteDensityBudget`
combines its two producer queries with its one inert residual observable. -/
structure Registration (Residual : Type uResidual)
    (AmbientItem : Residual → Type uDemand)
    (ambient : (residual : Residual) →
      Core.Finite.Enumeration (AmbientItem residual))
    (Block : Residual → Type uPayer)
    (cover : (residual : Residual) → Block residual →
      List (AmbientItem residual)) where
  /-- Primitive finite interaction.  In the graph adapter this is adjacency;
  Core only sees a decidable symmetric relation. -/
  Interaction : (residual : Residual) →
    AmbientItem residual → AmbientItem residual → Prop
  interactionDecidable : (residual : Residual) →
    (left right : AmbientItem residual) →
      Decidable (Interaction residual left right)
  interactionSymmetric : ∀ residual left right,
    Interaction residual left right → Interaction residual right left
  baseline : Residual → Nat
  /-- The baseline is bounded by the literal ambient interaction load.  This
  is an inherited residual invariant, not an accounting conclusion. -/
  minimumLoad : ∀ residual item, item ∈ (ambient residual).values →
    baseline residual ≤
      ((ambient residual).values.countP fun other =>
        @decide (Interaction residual item other)
          (interactionDecidable residual item other))

end Hypostructure.Core.Strategy.BoundaryDemandAccounting
