import Hypostructure.Core.Finite.Enumeration
import Hypostructure.Core.Strategy.SupportComplementNormalizationSemantics

/-!
# Residual-indexed boundary-demand accounting semantics

Inert presentation data for the CT4 → CT14 composition implemented in
`BoundaryDemandAccounting.lean`.  The record supplies only the primitive
demand, payer, eligibility, weight, capacity, aggregate, and labelling
semantics.  Core supplies the exact normalized-support ledger published by a
completed `SupportComplementNormalization`, and the exact assigned total
generated by CT4.
-/

namespace Hypostructure.Core.Strategy.BoundaryDemandAccounting

universe uResidual uDemand uPayer uMember uLabel

open Hypostructure.Core.Strategy

/-- Exact numeric ledger published by one completed boundary accounting.

The last three fields are the window/remainder coordinates of manuscript node
`[29]`.  They are not recomputed here: they are the three counts CT9 already
published on the normalized-support ledger this node reads, copied verbatim
onto the accounting entry so that a consumer downstream of the accounting
boundary -- where the normalization ledger itself no longer travels -- can
still state the node-`[29]` supply account in the manuscript's own variables:

* `ambientCount` is `n`, the ambient item schedule CT9 partitioned;
* `selectedCount` is `|W|`, the part covered by the selected packing (for the
  Erdős–Gyárfás presentation that is `13 p₁₃`, the vertices of the packed
  windows, *not* the number of windows);
* `complementCount` is `|R|`, the normalized remainder.

`memberCapacity` in `BoundaryDemandAccounting.lean` already multiplies the
registered per-member capacity rate by `selectedCount`; these fields publish
the same three numbers rather than a second, independently derived copy. -/
structure Summary where
  demandCount : Nat
  payerCount : Nat
  requiredTotal : Nat
  assignedTotal : Nat
  capacityTotal : Nat
  /-- `n`: CT9's ambient item count on the normalized-support ledger. -/
  ambientCount : Nat
  /-- `|W|`: CT9's selected fibre count on the same ledger. -/
  selectedCount : Nat
  /-- `|R|`: CT9's complementary fibre count on the same ledger. -/
  complementCount : Nat
  deriving DecidableEq, Repr, Inhabited

/-- Residual-owned demand/payer presentation together with the aggregate
members CT14 compares.

Every field is indexed by the residual alone, and the two aggregate
observations are per-member *rates*.  The exact normalized-support ledger is
not a registration field: Core constructs it as a typed ledger query from the
actual producer entry and multiplies the registered capacity rate by its
extensive selected count in the profile, exactly as `FiniteDensityBudget`
combines its two producer queries with its one inert residual observable. -/
structure Registration (Residual : Type uResidual) where
  Demand : Residual → Type uDemand
  Payer : Residual → Type uPayer
  demands : (residual : Residual) → Core.Finite.Enumeration (Demand residual)
  payers : (residual : Residual) → Core.Finite.Enumeration (Payer residual)
  Eligible : (residual : Residual) → Demand residual → Payer residual → Prop
  eligibleDecidable : (residual : Residual) →
    (demand : Demand residual) → (payer : Payer residual) →
      Decidable (Eligible residual demand payer)
  demandWeight : (residual : Residual) → Demand residual → Nat
  payerCapacity : (residual : Residual) → Payer residual → Nat
  Member : Residual → Type uMember
  Label : Residual → Type uLabel
  members : (residual : Residual) → Core.Finite.Enumeration (Member residual)
  /-- Per-member demand mass CT14 accumulates on the lower side. -/
  memberLowerMass : (residual : Residual) → Member residual → Nat
  /-- Per-member capacity *rate*.  Core multiplies it by the exact selected
  count published by the preceding support-complement normalization. -/
  memberCapacityRate : (residual : Residual) → Member residual → Nat
  memberLabel : (residual : Residual) → Member residual → Label residual
  labelDecidableEq : (residual : Residual) → DecidableEq (Label residual)

end Hypostructure.Core.Strategy.BoundaryDemandAccounting
