import Hypostructure.Core.Finite.Enumeration
import Hypostructure.Core.Strategy.SupportComplementNormalizationSemantics

/-!
# Residual-indexed boundary-demand accounting semantics

Inert presentation data for the CT4 → CT14 composition implemented in
`BoundaryDemandAccounting.lean`.  The record supplies only the primitive
demand, payer, eligibility, weight, capacity, aggregate, and labelling
semantics.  Core supplies the exact normalized-support ledger published by a
completed `SupportComplementNormalization`, and the exact assigned total
generated by CT4.
-/

namespace Hypostructure.Core.Strategy.BoundaryDemandAccounting

universe uResidual uDemand uPayer uMember uLabel

open Hypostructure.Core.Strategy

namespace FiniteInteraction

universe uItem

/-- Total interaction load from one item into an exact finite schedule. -/
def load {Item : Type uItem} (incidence : Item → Item → Nat)
    (schedule : Core.Finite.Enumeration Item) (item : Item) : Nat :=
  (schedule.values.map (incidence item)).sum

/-- Positive baseline deficiency on an exact finite schedule. -/
def positiveDeficiency {Item : Type uItem} (baseline : Nat)
    (internal : Item → Nat) (schedule : Core.Finite.Enumeration Item) : Nat :=
  (schedule.values.map fun item => baseline - internal item).sum

/-- Total boundary interaction emitted by an exact finite schedule. -/
def boundarySupply {Item : Type uItem} (boundary : Item → Nat)
    (schedule : Core.Finite.Enumeration Item) : Nat :=
  (schedule.values.map boundary).sum

/-- Summed positive deficiency is bounded by the literal boundary supply.

This is the domain-neutral arithmetic used by the sealed CT4 operation.  The
only hypothesis is the pointwise load split supplied by the finite interaction
ledger; no graph, PDE, path order, or paper constant occurs in the theorem. -/
theorem positiveDeficiency_le_boundarySupply
    {Item : Type uItem} (baseline : Nat) (internal boundary : Item → Nat)
    (schedule : Core.Finite.Enumeration Item)
    (minimumLoad : ∀ item ∈ schedule.values,
      baseline ≤ internal item + boundary item) :
    positiveDeficiency baseline internal schedule ≤
      boundarySupply boundary schedule := by
  unfold positiveDeficiency boundarySupply
  apply List.sum_le_sum
  intro item member
  have := minimumLoad item member
  omega

/-- The block-side account is additive over the literal finite block table.
The block table, its order, and its baseline are parameters of the generic
operation; no application constant is embedded in this theorem. -/
theorem sum_boundary_add_internal_eq
    {Item Block : Type uItem}
    (baseline order : Nat)
    (blocks : Core.Finite.Enumeration Block)
    (boundary internal surplus : Block → Nat)
    (localAccount : ∀ block ∈ blocks.values,
      boundary block + internal block = baseline * order + surplus block) :
    (blocks.values.map boundary).sum +
        (blocks.values.map internal).sum =
      (baseline * order) * blocks.card +
        (blocks.values.map surplus).sum := by
  rw [Core.Finite.Enumeration.card]
  calc
    (blocks.values.map boundary).sum + (blocks.values.map internal).sum =
        (blocks.values.map (fun block => boundary block + internal block)).sum := by
          simp [List.sum_map_add]
    _ = (blocks.values.map (fun block => baseline * order + surplus block)).sum := by
          exact congrArg List.sum (List.map_congr_left localAccount)
    _ = (baseline * order) * blocks.values.length +
          (blocks.values.map surplus).sum := by
          rw [List.sum_map_add]
          simp [List.map_const, Nat.mul_comm]

/-- The surplus-aware ceiling is the nonnegative part of the exact block
account. Consumers use this theorem through the ordinary accumulated ledger;
they never unfold or reconstruct the block schedule. -/
theorem boundary_le_block_baseline_add_surplus
    {Item Block : Type uItem}
    (baseline order : Nat)
    (blocks : Core.Finite.Enumeration Block)
    (boundary internal surplus : Block → Nat)
    (internal_nonnegative : 0 ≤ (blocks.values.map internal).sum)
    (account :
      (blocks.values.map boundary).sum + (blocks.values.map internal).sum =
        (baseline * order) * blocks.card + (blocks.values.map surplus).sum) :
    (blocks.values.map boundary).sum ≤
      (baseline * order) * blocks.card + (blocks.values.map surplus).sum := by
  omega

/-! Named framework corollaries for the finite interaction obligations used by
the sealed strategy.  They are intentionally expressed only through incoming
finite schedules and ledger equations. -/

theorem deficiency_surplus_split
    {Item : Type uItem} (baseline : Nat) (internal boundary : Item → Nat)
    (schedule : Core.Finite.Enumeration Item) :
    positiveDeficiency baseline internal schedule =
      (schedule.values.map fun item => baseline - internal item).sum := rfl

theorem stub_positive
    {Item : Type uItem} (baseline : Nat) (internal boundary : Item → Nat)
    (schedule : Core.Finite.Enumeration Item)
    (minimumLoad : ∀ item ∈ schedule.values,
      baseline ≤ internal item + boundary item) :
    positiveDeficiency baseline internal schedule ≤
      boundarySupply boundary schedule :=
  positiveDeficiency_le_boundarySupply baseline internal boundary schedule minimumLoad

theorem exact_window_join_identity
    {Block : Type uItem} (baseline order : Nat)
    (blocks : Core.Finite.Enumeration Block)
    (boundary internal surplus : Block → Nat)
    (account : ∀ block ∈ blocks.values,
      boundary block + internal block = baseline * order + surplus block) :
    (blocks.values.map boundary).sum + (blocks.values.map internal).sum =
      (baseline * order) * blocks.card + (blocks.values.map surplus).sum :=
  sum_boundary_add_internal_eq baseline order blocks boundary internal surplus account

theorem surplus_aware_window_stub
    {Block : Type uItem} (baseline order : Nat)
    (blocks : Core.Finite.Enumeration Block)
    (boundary internal surplus : Block → Nat)
    (account :
      (blocks.values.map boundary).sum + (blocks.values.map internal).sum =
        (baseline * order) * blocks.card + (blocks.values.map surplus).sum) :
    (blocks.values.map boundary).sum ≤
      (baseline * order) * blocks.card + (blocks.values.map surplus).sum := by
  exact boundary_le_block_baseline_add_surplus baseline order blocks boundary
    internal surplus (by omega) account

end FiniteInteraction

/-- Exact numeric ledger published by one completed boundary accounting.

The last three fields are the window/remainder coordinates of manuscript node
`[29]`.  They are not recomputed here: they are the three counts CT9 already
published on the normalized-support ledger this node reads, copied verbatim
onto the accounting entry so that a consumer downstream of the accounting
boundary -- where the normalization ledger itself no longer travels -- can
still state the node-`[29]` supply account in the manuscript's own variables:

* `ambientCount` is `n`, the ambient item schedule CT9 partitioned;
* `selectedCount` is `|W|`, the part covered by the selected packing (for the
  Erdős–Gyárfás presentation that is `13 p₁₃`, the vertices of the packed
  windows, *not* the number of windows);
* `complementCount` is `|R|`, the normalized remainder.

`memberCapacity` in `BoundaryDemandAccounting.lean` already multiplies the
registered per-member capacity rate by `selectedCount`; these fields publish
the same three numbers rather than a second, independently derived copy. -/
structure Summary where
  demandCount : Nat
  payerCount : Nat
  requiredTotal : Nat
  assignedTotal : Nat
  capacityTotal : Nat
  /-- `n`: CT9's ambient item count on the normalized-support ledger. -/
  ambientCount : Nat
  /-- `|W|`: CT9's selected fibre count on the same ledger. -/
  selectedCount : Nat
  /-- `|R|`: CT9's complementary fibre count on the same ledger. -/
  complementCount : Nat
  deriving DecidableEq, Repr, Inhabited

/-- Residual-owned demand/payer presentation together with the aggregate
members CT14 compares.

Every field is indexed by the residual alone, and the two aggregate
observations are per-member *rates*.  The exact normalized-support ledger is
not a registration field: Core constructs it as a typed ledger query from the
actual producer entry and multiplies the registered capacity rate by its
extensive selected count in the profile, exactly as `FiniteDensityBudget`
combines its two producer queries with its one inert residual observable. -/
structure Registration (Residual : Type uResidual) where
  Demand : Residual → Type uDemand
  Payer : Residual → Type uPayer
  demands : (residual : Residual) → Core.Finite.Enumeration (Demand residual)
  payers : (residual : Residual) → Core.Finite.Enumeration (Payer residual)
  Eligible : (residual : Residual) → Demand residual → Payer residual → Prop
  eligibleDecidable : (residual : Residual) →
    (demand : Demand residual) → (payer : Payer residual) →
      Decidable (Eligible residual demand payer)
  demandWeight : (residual : Residual) → Demand residual → Nat
  payerCapacity : (residual : Residual) → Payer residual → Nat
  Member : Residual → Type uMember
  Label : Residual → Type uLabel
  members : (residual : Residual) → Core.Finite.Enumeration (Member residual)
  /-- Per-member demand mass CT14 accumulates on the lower side. -/
  memberLowerMass : (residual : Residual) → Member residual → Nat
  /-- Per-member capacity *rate*.  Core multiplies it by the exact selected
  count published by the preceding support-complement normalization. -/
  memberCapacityRate : (residual : Residual) → Member residual → Nat
  memberLabel : (residual : Residual) → Member residual → Label residual
  labelDecidableEq : (residual : Residual) → DecidableEq (Label residual)

end Hypostructure.Core.Strategy.BoundaryDemandAccounting
