import HypostructureErdos64EG.Assembly.Absorbed.Boundary
import HypostructureErdos64EG.Assembly.Absorbed.FanCharge
import HypostructureErdos64EG.Assembly.Absorbed.Prerequisites
import HypostructureErdos64EG.Assembly.Absorbed.Residual
import HypostructureErdos64EG.Assembly.Basic
import HypostructureErdos64EG.Assembly.Cold.Barrier
import HypostructureErdos64EG.Assembly.Cold.Entropy
import HypostructureErdos64EG.Assembly.Cold.Germs
import HypostructureErdos64EG.Assembly.Entry
import HypostructureErdos64EG.Assembly.Final
import HypostructureErdos64EG.Assembly.NearCubic.Boundary
import HypostructureErdos64EG.Assembly.NearCubic.Local
import HypostructureErdos64EG.Assembly.NearCubic.Replacement
import HypostructureErdos64EG.Assembly.NearCubic.Survivor
import HypostructureErdos64EG.Assembly.NetCharge.Boundary
import HypostructureErdos64EG.Assembly.NetCharge.Continuation
import HypostructureErdos64EG.Assembly.RouteEight.Boundary
import HypostructureErdos64EG.Assembly.RouteEight.Local
import HypostructureErdos64EG.Assembly.RouteEight.RateFailure
import HypostructureErdos64EG.Assembly.RouteEight.Residual
import HypostructureErdos64EG.Assembly.RouteEight.TypeBContinuation
import HypostructureErdos64EG.Assembly.Surplus.Boundary
import HypostructureErdos64EG.Assembly.Surplus.Local
import HypostructureErdos64EG.Assembly.Surplus.Strict
import HypostructureErdos64EG.Assembly.Surplus.TypeBContinuation
import HypostructureErdos64EG.Assembly.TypeA.DecoratedHandoff
import HypostructureErdos64EG.Assembly.TypeA.ExitFiveToSeven
import HypostructureErdos64EG.Assembly.TypeA.ExitFiveToSevenSilent
import HypostructureErdos64EG.Assembly.TypeA.ExitFourChain
import HypostructureErdos64EG.Assembly.TypeA.ExitFourChainSilent
import HypostructureErdos64EG.Assembly.TypeA.ExitFourDischargedRetest
import HypostructureErdos64EG.Assembly.TypeA.LowSurplusContinuation
import HypostructureErdos64EG.Assembly.TypeA.SilentExitChain
import HypostructureErdos64EG.Assembly.TypeA.VisibleExitChain
import HypostructureErdos64EG.Assembly.TypeA.VisibleExitFour
import HypostructureErdos64EG.Assembly.TypeB.Certificate
import HypostructureErdos64EG.Assembly.TypeB.ChargedRoute
import HypostructureErdos64EG.Assembly.TypeB.Continuation
import HypostructureErdos64EG.Assembly.TypeB.DecoratedContinuation
import HypostructureErdos64EG.Assembly.TypeB.HighSurplusContinuation
import HypostructureErdos64EG.Assembly.TypeB.Internal.Certificate
import HypostructureErdos64EG.Assembly.TypeB.NearCubicCertificate

/-!
# Erdős–Gyárfás assembly

Compatibility import for the complete assembly. For local proof development,
import or build the specific `HypostructureErdos64EG.Assembly.*` module.
-/
